force-app/main/default/objects/Account/fields/DX_Other__c.field-meta.xml
<CustomField>
    <fullName>DX_Other__c</fullName>
    <defaultValue>false</defaultValue>
    <label>帳票_その他集計_EN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/S__c.field-meta.xml
<CustomField>
    <fullName>S__c</fullName>
    <label>S</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EN_Report__mdt/EN_Report__mdt.object-meta.xml
<CustomObject>
    <label>EN_帳票用</label>
</CustomObject>

force-app/main/default/objects/EN_Report__mdt/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>担当部署</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EN_Report__mdt/fields/OrderBy__c.field-meta.xml
<CustomField>
    <fullName>OrderBy__c</fullName>
    <label>順番</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/en_yojitsu__c.object-meta.xml
<CustomObject>
    <label>EN予実管理</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>予実管理番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/en_yojitsu__c/fields/en_juchu12__c.field-meta.xml
<CustomField>
    <fullName>en_juchu12__c</fullName>
    <label>受注金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/fields/en_jutyuarari__c.field-meta.xml
<CustomField>
    <fullName>en_jutyuarari__c</fullName>
    <label>受注粗利金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/fields/en_shodans__c.field-meta.xml
<CustomField>
    <fullName>en_shodans__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>商談</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>EN予実管理</relationshipLabel>
    <relationshipName>en_shodansan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/FormCreation__c.object-meta.xml
<CustomObject>
    <label>帳票作成用</label>
    <nameField>
        <label>帳票作成用名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FormCreation__c/fields/A__c.field-meta.xml
<CustomField>
    <fullName>A__c</fullName>
    <label>A</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/B__c.field-meta.xml
<CustomField>
    <fullName>B__c</fullName>
    <label>B</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/C__c.field-meta.xml
<CustomField>
    <fullName>C__c</fullName>
    <label>C</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/D__c.field-meta.xml
<CustomField>
    <fullName>D__c</fullName>
    <label>D</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/E__c.field-meta.xml
<CustomField>
    <fullName>E__c</fullName>
    <label>E</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/F__c.field-meta.xml
<CustomField>
    <fullName>F__c</fullName>
    <label>F</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/G__c.field-meta.xml
<CustomField>
    <fullName>G__c</fullName>
    <label>G</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/H__c.field-meta.xml
<CustomField>
    <fullName>H__c</fullName>
    <label>H</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/I__c.field-meta.xml
<CustomField>
    <fullName>I__c</fullName>
    <label>I</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/J__c.field-meta.xml
<CustomField>
    <fullName>J__c</fullName>
    <label>J</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/K__c.field-meta.xml
<CustomField>
    <fullName>K__c</fullName>
    <label>K</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/L__c.field-meta.xml
<CustomField>
    <fullName>L__c</fullName>
    <label>L</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/M__c.field-meta.xml
<CustomField>
    <fullName>M__c</fullName>
    <label>M</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/N__c.field-meta.xml
<CustomField>
    <fullName>N__c</fullName>
    <label>N</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/O__c.field-meta.xml
<CustomField>
    <fullName>O__c</fullName>
    <label>O</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/OrderBy__c.field-meta.xml
<CustomField>
    <fullName>OrderBy__c</fullName>
    <label>並び順</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/P__c.field-meta.xml
<CustomField>
    <fullName>P__c</fullName>
    <label>P</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/Q__c.field-meta.xml
<CustomField>
    <fullName>Q__c</fullName>
    <label>Q</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/R__c.field-meta.xml
<CustomField>
    <fullName>R__c</fullName>
    <label>R</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/S__c.field-meta.xml
<CustomField>
    <fullName>S__c</fullName>
    <label>S</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/T__c.field-meta.xml
<CustomField>
    <fullName>T__c</fullName>
    <label>T</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/Title1__c.field-meta.xml
<CustomField>
    <fullName>Title1__c</fullName>
    <label>Title1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/U__c.field-meta.xml
<CustomField>
    <fullName>U__c</fullName>
    <label>U</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/V__c.field-meta.xml
<CustomField>
    <fullName>V__c</fullName>
    <label>V</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FormCreation__c/fields/W__c.field-meta.xml
<CustomField>
    <fullName>W__c</fullName>
    <label>W</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>作成時の野原HD所有者の部署情報を表示</description>
    <label>担当部署</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/en_ankenkubun__c.field-meta.xml
<CustomField>
    <fullName>en_ankenkubun__c</fullName>
    <label>案件区分</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/EN_LastMonthzyutyuumikomi__c.field-meta.xml
<CustomField>
    <fullName>EN_LastMonthzyutyuumikomi__c</fullName>
    <label>先月見込み</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EN_zyutyuumikomi</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/en_mokuhyouriekigaku__c.field-meta.xml
<CustomField>
    <fullName>en_mokuhyouriekigaku__c</fullName>
    <label>目標利益額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/en_zyutyuararigaku__c.field-meta.xml
<CustomField>
    <fullName>en_zyutyuararigaku__c</fullName>
    <label>受注粗利額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/en_zyutyukingaku__c.field-meta.xml
<CustomField>
    <fullName>en_zyutyukingaku__c</fullName>
    <label>受注金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/en_zyutyuubi__c.field-meta.xml
<CustomField>
    <fullName>en_zyutyuubi__c</fullName>
    <label>受注日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/EN_zyutyuumikomi__c.field-meta.xml
<CustomField>
    <fullName>EN_zyutyuumikomi__c</fullName>
    <label>今月見込み</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EN_zyutyuumikomi</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/en_zyutyuumokuhyougaku__c.field-meta.xml
<CustomField>
    <fullName>en_zyutyuumokuhyougaku__c</fullName>
    <label>受注目標額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/NHR_EN_SalesReportBatch2.cls
/*
 * 1_2を作成
 */
global without sharing class NHR_EN_SalesReportBatch2 implements Database.Batchable<sObject>, Database.Stateful{
    static final String ACTUAL = '実績';
    static final String BUDGET = '予算';
    global List<Opportunity> addOppList {get;set;}
    global Map<String ,FormCreation__c> excelMap1_1 {get;set;}
    global Map<String ,FormCreation__c> excelMap1_2 {get;set;}
    global Map<String ,FormCreation__c> excelMap2 {get;set;}
    global Map<String ,FormCreation__c> excelMap3 {get;set;}
    global Map<String ,FormCreation__c> excelMap4 {get;set;}
    global Map<String ,String> yearMap {get;set;}
    global Map<String ,EN_Report__mdt> reportMap {get;set;}
    global String deStr {get;set;}
    global String unitStr {get;set;}
    global String userId {get;set;}
    global Date startDate {get;set;}
    global Date endDate {get;set;}
    global Date LastMonthStartDate {get;set;}
    global Date LastMonthEndDate {get;set;}
    global NHR_EN_SalesReportBatch2
        (Map<String ,FormCreation__c> inExcelMap1_1
         ,Map<String ,FormCreation__c> inExcelMap1_2
         ,Map<String ,FormCreation__c> inExcelMap2
         ,Map<String ,FormCreation__c> inExcelMap3
         ,Map<String ,FormCreation__c> inExcelMap4
         ,String inDeStr
         ,String inUnit
         ,String userId
         ,Date inStartDate
         ,Date inEndDate
         ,Date inLastMonthStartDate
         ,Date inLastMonthEndDate
         ,Map<String ,EN_Report__mdt> inReportMap
         ,Map<String ,String> inYearMap)
    {
        this.excelMap1_1 = inExcelMap1_1;
        this.excelMap1_2 = inExcelMap1_2;
        this.excelMap2 = inExcelMap2;
        this.excelMap3 = inExcelMap3;
        this.excelMap4 = inExcelMap4;
        this.deStr = inDeStr;
        this.unitStr = inUnit;
        this.userId = userId;
        this.startDate = inStartDate;
        this.endDate = inEndDate;
        this.LastMonthStartDate = inLastMonthStartDate;
        this.LastMonthEndDate = inLastMonthEndDate;
        this.reportMap = inReportMap;
        this.yearMap = inYearMap;
    }

    //データ取得
    global Database.QueryLocator start(Database.BatchableContext BC){
        system.debug('NHR_EN_SalesReportBatch2');
        system.debug('this.excelMap3:' + this.excelMap3);

        Set<String> tantobusyo = reportMap.keySet();
    	String query = NHR_Dao.get_NHR_EN_SalesReportBatch2(this.unitStr ,this.userId);
        //商談（営繕工事、材料販売）
        addOppList = Database.query(NHR_Dao.get_NHR_EN_AddOppGet(this.unitStr ,this.userId));

        return Database.getQueryLocator(query);
    }

    //開始
    global void execute(Database.BatchableContext BC, List<Opportunity> scopes){
        for(Opportunity obj : scopes) {
            FormCreation__c tempInfo = new FormCreation__c();
            if (this.unitStr == NHR_Constant.UNIT1) {
                String tantobusyoStr = obj.Department__c;
                if (tantobusyoStr == '営業部') {
                    tantobusyoStr = '営業１課';
                }
                //営業所単位
                if (!excelMap1_2.containsKey(tantobusyoStr)) {
                    integer orderStart = excelMap1_2.size();
                    excelMap1_2.put(tantobusyoStr ,setFC('Sales1_2'+ deStr, tantobusyoStr, orderStart * 10 + 1));
                }
                tempInfo = excelMap1_2.get(tantobusyoStr);
            } else if (this.unitStr == NHR_Constant.UNIT2) {
                //チーム単位
                if (!excelMap1_2.containsKey(obj.OwnerId)) {
                    integer orderStart = excelMap1_2.size();
                    excelMap1_2.put(obj.OwnerId ,setFC('Sales1_2'+ deStr, obj.Owner.Name, orderStart * 10 + 1));
                }
                tempInfo = excelMap1_2.get(obj.OwnerId);
            } else if (this.unitStr == NHR_Constant.UNIT3 || this.unitStr == NHR_Constant.UNIT4) {
                String tempKey = '';
                String tempName = '';
                integer orderStart = 0;
                
                if(obj.Account.DX_Other__c) {
                    tempKey = 'DX_Other__c';
                    tempName = 'その他';
                    orderStart = 900;
                    
                } else {
                    tempKey = obj.AccountId;
                    tempName = obj.Account.Name;
                    orderStart = excelMap1_2.size();
                }
                //個人単位
                if (!excelMap1_2.containsKey(tempKey)) {
                    //integer orderStart = excelMap1_2.size();
                    excelMap1_2.put(tempKey ,setFC('Sales1_2'+ userId, tempName, orderStart * 10 + 1));
                }
                tempInfo = excelMap1_2.get(tempKey);

            }
            //tempInfo = excelMap1_2.get(obj.Department__c);

            //前月受注見込額と実績額
            if (obj.EN_LastMonthzyutyuumikomi__c == '受注') {
                tempInfo.B__c += (obj.en_zyutyuumokuhyougaku__c == null ? 0 : obj.en_zyutyuumokuhyougaku__c);
                tempInfo.C__c += (obj.en_mokuhyouriekigaku__c == null ? 0 : obj.en_mokuhyouriekigaku__c);

                if(tempInfo.Title1__c == '株式会社大林組　大阪本店 エンジ大阪'){system.debug(obj.en_shodansan__r);system.debug(obj.en_shodansan__r.size());} 
                if (obj.en_shodansan__r != NULL && obj.en_shodansan__r.size() > 0) {
                    for (en_yojitsu__c obj2 : obj.en_shodansan__r) {
                        tempInfo.E__c += (obj2.en_juchu12__c == null ? 0 : obj2.en_juchu12__c);
                        tempInfo.F__c += (obj2.en_jutyuarari__c == null ? 0 : obj2.en_jutyuarari__c);
                    }
                }
            }
            //当月受注見込額
            if (obj.EN_zyutyuumikomi__c == '受注') {
                tempInfo.H__c += (obj.en_zyutyuumokuhyougaku__c == null ? 0 : obj.en_zyutyuumokuhyougaku__c);
                tempInfo.I__c += (obj.en_mokuhyouriekigaku__c == null ? 0 : obj.en_mokuhyouriekigaku__c);
            }
        }
    }

     //完了
    global void finish(Database.BatchableContext BC)
    {
        EN_Report__mdt Osaka = EN_Report__mdt.getInstance('Osaka');
        //完了後の処理があれば
        //小計
        if ( (this.unitStr == NHR_Constant.UNIT2 && this.deStr == Osaka.Department__c)
            || (this.unitStr == NHR_Constant.UNIT3 && this.deStr == Osaka.MasterLabel)
            || (this.unitStr == NHR_Constant.UNIT4 && this.userId == '005RC000000EAynYAG'))
        {
        } else {
            setSumPre();
        }
        setSum1_2();

        //１．受注計画に対する実績数値の確認
        insert excelMap1_2.values();

        //完了後の処理があれば
        NHR_EN_SalesReportBatch3 myBatchObject = new NHR_EN_SalesReportBatch3
            (excelMap1_1
             ,excelMap1_2
             ,excelMap2
             ,excelMap3
             ,excelMap4
             ,deStr
             ,unitStr
             ,userId
             ,startDate
             ,endDate
             ,LastMonthStartDate
             ,LastMonthEndDate
             ,reportMap
             ,yearMap
            );
        Database.executeBatch(myBatchObject,2000);

    }
    
    /**
     * 集計事前処理
     */
    private void setSumPre(){
        Set<String> tantobusyo = reportMap.keySet();
        //商談（営繕工事、材料販売）
        addOppList = Database.query(NHR_Dao.get_NHR_EN_AddOppGet(this.unitStr ,this.userId));
        
        FormCreation__c tempOppInfo1_2_1 = new FormCreation__c();
        FormCreation__c tempOppInfo1_2_2 = new FormCreation__c();
        Date NextMonthStartDate = LastMonthStartDate.addMonths(2);
        
        if (this.unitStr == NHR_Constant.UNIT3 || this.unitStr == NHR_Constant.UNIT4) {
            excelMap1_2.put('addOpp1', setFC('Sales1_2'+ this.userId,'材料販売',9001));
            excelMap1_2.put('addOpp2', setFC('Sales1_2'+ this.userId,'営繕工事',9002));
            
            tempOppInfo1_2_1 = excelMap1_2.get('addOpp1');
            tempOppInfo1_2_2 = excelMap1_2.get('addOpp2');

        } else {            
            excelMap1_2.put('addOpp1', setFC('Sales1_2'+ this.deStr,'材料販売',9001));
            excelMap1_2.put('addOpp2', setFC('Sales1_2'+ this.deStr,'営繕工事',9002));
            
            tempOppInfo1_2_1 = excelMap1_2.get('addOpp1');
            tempOppInfo1_2_2 = excelMap1_2.get('addOpp2');
            
        }
        
        for(Opportunity obj : addOppList) {
            if (obj.en_zyutyuubi__c >= LastMonthStartDate && obj.en_zyutyuubi__c <= LastMonthEndDate) {
                //前月受注見込額と実績額
                if (obj.en_ankenkubun__c == '材料販売') {
                    tempOppInfo1_2_1.B__c += (obj.en_zyutyuumokuhyougaku__c == null ? 0 : obj.en_zyutyuumokuhyougaku__c);
                    tempOppInfo1_2_1.C__c += (obj.en_mokuhyouriekigaku__c == null ? 0 : obj.en_mokuhyouriekigaku__c);
                    tempOppInfo1_2_1.E__c += (obj.en_zyutyukingaku__c == null ? 0 : obj.en_zyutyukingaku__c);
                    tempOppInfo1_2_1.F__c += (obj.en_zyutyuararigaku__c == null ? 0 : obj.en_zyutyuararigaku__c);
                } else {
                    tempOppInfo1_2_2.B__c += (obj.en_zyutyuumokuhyougaku__c == null ? 0 : obj.en_zyutyuumokuhyougaku__c);
                    tempOppInfo1_2_2.C__c += (obj.en_mokuhyouriekigaku__c == null ? 0 : obj.en_mokuhyouriekigaku__c);
                    tempOppInfo1_2_2.E__c += (obj.en_zyutyukingaku__c == null ? 0 : obj.en_zyutyukingaku__c);
                    tempOppInfo1_2_2.F__c += (obj.en_zyutyuararigaku__c == null ? 0 : obj.en_zyutyuararigaku__c);
                }
            } else if (obj.en_zyutyuubi__c > LastMonthEndDate && obj.en_zyutyuubi__c < NextMonthStartDate) {
                //当月受注見込額
                if (obj.en_ankenkubun__c == '材料販売') {
                    tempOppInfo1_2_1.H__c += (obj.en_zyutyuumokuhyougaku__c == null ? 0 : obj.en_zyutyuumokuhyougaku__c);
                    tempOppInfo1_2_1.I__c += (obj.en_mokuhyouriekigaku__c == null ? 0 : obj.en_mokuhyouriekigaku__c);
                } else {
                    tempOppInfo1_2_2.H__c += (obj.en_zyutyuumokuhyougaku__c == null ? 0 : obj.en_zyutyuumokuhyougaku__c);
                    tempOppInfo1_2_2.I__c += (obj.en_mokuhyouriekigaku__c == null ? 0 : obj.en_mokuhyouriekigaku__c);
                }
            }
        }
    }

    /**
     * 集計1_2
     */
    private void setSum1_2(){
        FormCreation__c sum = excelMap1_2.get('Sum');
        for (String keyStr : excelMap1_2.KeySet()) {
            FormCreation__c tempObj = excelMap1_2.get(keyStr);
            if ( keyStr != 'Sum') {
                sum.B__c += tempObj.B__c;
                sum.C__c += tempObj.C__c;
                sum.E__c += tempObj.E__c;
                sum.F__c += tempObj.F__c;
                sum.H__c += tempObj.H__c;
                sum.I__c += tempObj.I__c;

                tempObj.D__c = NHR_Dao.getDivision(tempObj.B__c ,tempObj.C__c);
                tempObj.G__c = NHR_Dao.getDivision(tempObj.E__c ,tempObj.F__c);
                tempObj.J__c = NHR_Dao.getDivision(tempObj.H__c ,tempObj.I__c);
                excelMap1_2.put(keyStr ,tempObj);
            }
        }

        sum.D__c = NHR_Dao.getDivision(sum.B__c ,sum.C__c);
        sum.G__c = NHR_Dao.getDivision(sum.E__c ,sum.F__c);
        sum.J__c = NHR_Dao.getDivision(sum.H__c ,sum.I__c);

        excelMap1_2.put('Sum' ,sum);

        if (excelMap1_2.size() < 5) {
            for ( integer i = excelMap1_2.size() ; i < 5 ; i++) {
                if (String.isNotBlank(this.userId) ) {
                    excelMap1_2.put( String.valueOf(i)  ,setFC('Sales1_2' + this.userId , '', i * 10 + 1));
                } else {
                    excelMap1_2.put( String.valueOf(i)  ,setFC('Sales1_2' + this.deStr , '', i * 10 + 1));
                }

            }
        }

        for (String key : excelMap1_2.keySet()) {
            FormCreation__c  tempInfo = excelMap1_2.get(key);
                tempInfo = set1000Tani(tempInfo);
                excelMap1_2.put(key ,tempInfo);
        }
    }

    private FormCreation__c set1000Tani(FormCreation__c  tempInfo){
        tempInfo.B__c = tempInfo.B__c / 1000;
        tempInfo.C__c = tempInfo.C__c / 1000;
        tempInfo.E__c = tempInfo.E__c / 1000;
        tempInfo.F__c = tempInfo.F__c / 1000;
        tempInfo.H__c = tempInfo.H__c / 1000;
        tempInfo.I__c = tempInfo.I__c / 1000;
        tempInfo.K__c = tempInfo.K__c / 1000;
        tempInfo.L__c = tempInfo.L__c / 1000;
        tempInfo.P__c = tempInfo.P__c / 1000;
        tempInfo.Q__c = tempInfo.Q__c / 1000;
        tempInfo.S__c = tempInfo.S__c / 1000;
        tempInfo.T__c = tempInfo.T__c / 1000;
        return tempInfo;
    }

    public FormCreation__c setFC(String Name , String Title1 ,integer orderBy){
        FormCreation__c rec = new FormCreation__c();
        rec.Name = Name;
        rec.Title1__c = Title1;
        rec.orderBy__c = orderBy;
        rec.A__c = 0;
        rec.B__c = 0;
        rec.C__c = 0;
        rec.D__c = 0;
        rec.E__c = 0;
        rec.F__c = 0;
        rec.G__c = 0;
        rec.H__c = 0;
        rec.I__c = 0;
        rec.J__c = 0;
        rec.K__c = 0;
        rec.L__c = 0;
        rec.M__c = 0;
        rec.N__c = 0;
        rec.O__c = 0;
        rec.P__c = 0;
        rec.Q__c = 0;
        rec.R__c = 0;
        rec.S__c = 0;
        rec.T__c = 0;
        rec.U__c = 0;
        rec.V__c = 0;
        rec.W__c = 0;
        return rec;
    }
    
    public static void forTest() {
        String test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
    }

}