force-app/main/default/objects/Account/fields/ST_focustype_boukoubu__c.field-meta.xml
<CustomField>
    <fullName>ST_focustype_boukoubu__c</fullName>
    <label>重点フラグ_材料販売</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>積極拡大</fullName>
            </value>
            <value>
                <fullName>重要な維持</fullName>
            </value>
            <value>
                <fullName>維持メンテ</fullName>
            </value>
            <value>
                <fullName>メンテ</fullName>
                <isActive>false</isActive>
                <label>メンテ</label>
            </value>
            <value>
                <fullName>放置</fullName>
                <isActive>false</isActive>
                <label>放置</label>
            </value>
            <value>
                <fullName>積極</fullName>
                <isActive>false</isActive>
                <label>積極</label>
            </value>
            <value>
                <fullName>維持</fullName>
                <isActive>false</isActive>
                <label>維持</label>
            </value>
            <value>
                <fullName>重要な維持①</fullName>
                <isActive>false</isActive>
                <label>重要な維持①</label>
            </value>
            <value>
                <fullName>重要な維持②</fullName>
                <isActive>false</isActive>
                <label>重要な維持②</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ST_focustype_kouji__c.field-meta.xml
<CustomField>
    <fullName>ST_focustype_kouji__c</fullName>
    <label>重点フラグ_工事</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>積極拡大</fullName>
            </value>
            <value>
                <fullName>重要な維持</fullName>
            </value>
            <value>
                <fullName>維持メンテ</fullName>
            </value>
            <value>
                <fullName>メンテ</fullName>
                <isActive>false</isActive>
                <label>メンテ</label>
            </value>
            <value>
                <fullName>放置</fullName>
                <isActive>false</isActive>
                <label>放置</label>
            </value>
            <value>
                <fullName>積極</fullName>
                <isActive>false</isActive>
                <label>積極</label>
            </value>
            <value>
                <fullName>維持</fullName>
                <isActive>false</isActive>
                <label>維持</label>
            </value>
            <value>
                <fullName>重要な維持①</fullName>
                <isActive>false</isActive>
                <label>重要な維持①</label>
            </value>
            <value>
                <fullName>重要な維持②</fullName>
                <isActive>false</isActive>
                <label>重要な維持②</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ST_Orderamounttarget__c.field-meta.xml
<CustomField>
    <fullName>ST_Orderamounttarget__c</fullName>
    <label>受注金額目標</label>
    <summarizedField>Opportunity.ST_Orderamounttarget__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.steel_OrderDate__c</field>
        <operation>greaterOrEqual</operation>
        <value>7/1/2025</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.steel_OrderDate__c</field>
        <operation>lessOrEqual</operation>
        <value>6/30/2026</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.RecordTypeId</field>
        <operation>equals</operation>
        <value>スチール_工事, ノハラスチール_工事_目標</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>内定, 受注ST, 仕掛, 完成</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CommonRecordType.recordType-meta.xml
<RecordType>
    <fullName>CommonRecordType</fullName>
    <active>true</active>
    <label>01.共通_得意先</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/ST_Orderamounttarget__c.field-meta.xml
<CustomField>
    <fullName>ST_Orderamounttarget__c</fullName>
    <label>受注金額目標</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_Orderquantitytarget__c.field-meta.xml
<CustomField>
    <fullName>ST_Orderquantitytarget__c</fullName>
    <label>受注数量目標</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_suryou__c.field-meta.xml
<CustomField>
    <fullName>ST_suryou__c</fullName>
    <label>数量(t)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_zyutyuararigaku__c.field-meta.xml
<CustomField>
    <fullName>ST_zyutyuararigaku__c</fullName>
    <label>目標利益額ST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/RecordType_Steelzairyou_goal.recordType-meta.xml
<RecordType>
    <fullName>RecordType_Steelzairyou_goal</fullName>
    <active>true</active>
    <businessProcess>ノハラスチール_棒鋼部</businessProcess>
    <label>スチール_工事_材料販売_目標</label>
</RecordType>

force-app/main/default/objects/ST_Yojitsu_Snapshot__c/ST_Yojitsu_Snapshot__c.object-meta.xml
<CustomObject>
    <label>ST予実管理_スナップショット</label>
    <nameField>
        <displayFormat>STY-{0000000000}</displayFormat>
        <label>ST予実管理_スナップショットNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ST_Yojitsu_Snapshot__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>商談</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>ST予実管理_スナップショット</relationshipLabel>
    <relationshipName>OpportunitySTYojitsusSnapshots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NHR_ST_SegmentPropertyQuantityTest.cls
@isTest 
public with sharing class NHR_ST_SegmentPropertyQuantityTest {
    @isTest 
    static void test01() {
        createTestData();

        Database.executeBatch(new NHR_ST_SegmentPropertyQuantity(), 200);
        NHR_ST_SegmentPropertyQuantity.forTest();
    }

    static void createTestData(){
        Date theToday = Date.Today();
        Date forGetDay = Date.Today();
        if (theToday.month() == 7) {
            forGetDay = theToday.addMonths(-1);
        }

        Date startDate = NHR_Dao.getFiscalYearStartDate(forGetDay);
        Date endDate = NHR_Dao.getFiscalYearEndDate(forGetDay);

        String currentLastMonth = endDate.year() + '年' + endDate.month() + '月期';

        // 共通取引先のレコードタイプを取得
        String comAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CommonRecordType').getRecordTypeId();
        Account acc = new Account(Name = '株式会社A' , RecordTypeId = ComAccRecTypeId ,ST_Department__c = '事業一部', ST_focustype_kouji__c='積極', ST_focustype_boukoubu__c='積極');
        Account acc1 = new Account(Name = '株式会社B' , RecordTypeId = ComAccRecTypeId ,ST_Department__c = '事業二部');
        insert new List<Account>{ acc, acc1 };

        String opportunityRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('RecordType_Steelzairyou_goal').getRecordTypeId();

        List<Opportunity> opportunities = new List<Opportunity>();
        Opportunity o1 = new Opportunity(Name = '株式会社B 事業1部目標',StageName = 'A',AccountId = acc.Id, ST_Orderamounttarget__c = 100, 
        ST_Orderquantitytarget__c = 100, ST_zyutyuararigaku__c = 100, CloseDate = Date.today(), RecordTypeId = opportunityRecordTypeId);
        opportunities.add(o1);

        Opportunity o2 = new Opportunity(Name = '株式会社B 事業1部目標',StageName = 'C',AccountId = acc1.Id, ST_Orderamounttarget__c = 100, 
        ST_Orderquantitytarget__c = 100, ST_zyutyuararigaku__c = 100, CloseDate = Date.today(), RecordTypeId = opportunityRecordTypeId);
        opportunities.add(o2);
        insert opportunities;

        ST_Yojitsu_Snapshot__c snapshot01 = new ST_Yojitsu_Snapshot__c(Opportunity__c=o1.Id, ST_suryou__c=100);
        ST_Yojitsu_Snapshot__c snapshot02 = new ST_Yojitsu_Snapshot__c(Opportunity__c=o2.Id, ST_suryou__c=100);
        insert new List<ST_Yojitsu_Snapshot__c>{ snapshot01, snapshot02 };
    }
}