force-app/main/default/objects/Account/fields/ST_focustype_boukoubu__c.field-meta.xml
<CustomField>
    <fullName>ST_focustype_boukoubu__c</fullName>
    <label>重点フラグ_材料販売</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>積極拡大</fullName>
            </value>
            <value>
                <fullName>重要な維持</fullName>
            </value>
            <value>
                <fullName>維持メンテ</fullName>
            </value>
            <value>
                <fullName>メンテ</fullName>
                <isActive>false</isActive>
                <label>メンテ</label>
            </value>
            <value>
                <fullName>放置</fullName>
                <isActive>false</isActive>
                <label>放置</label>
            </value>
            <value>
                <fullName>積極</fullName>
                <isActive>false</isActive>
                <label>積極</label>
            </value>
            <value>
                <fullName>維持</fullName>
                <isActive>false</isActive>
                <label>維持</label>
            </value>
            <value>
                <fullName>重要な維持①</fullName>
                <isActive>false</isActive>
                <label>重要な維持①</label>
            </value>
            <value>
                <fullName>重要な維持②</fullName>
                <isActive>false</isActive>
                <label>重要な維持②</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ST_focustype_kouji__c.field-meta.xml
<CustomField>
    <fullName>ST_focustype_kouji__c</fullName>
    <label>重点フラグ_工事</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>積極拡大</fullName>
            </value>
            <value>
                <fullName>重要な維持</fullName>
            </value>
            <value>
                <fullName>維持メンテ</fullName>
            </value>
            <value>
                <fullName>メンテ</fullName>
                <isActive>false</isActive>
                <label>メンテ</label>
            </value>
            <value>
                <fullName>放置</fullName>
                <isActive>false</isActive>
                <label>放置</label>
            </value>
            <value>
                <fullName>積極</fullName>
                <isActive>false</isActive>
                <label>積極</label>
            </value>
            <value>
                <fullName>維持</fullName>
                <isActive>false</isActive>
                <label>維持</label>
            </value>
            <value>
                <fullName>重要な維持①</fullName>
                <isActive>false</isActive>
                <label>重要な維持①</label>
            </value>
            <value>
                <fullName>重要な維持②</fullName>
                <isActive>false</isActive>
                <label>重要な維持②</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ST_Orderamounttarget__c.field-meta.xml
<CustomField>
    <fullName>ST_Orderamounttarget__c</fullName>
    <label>受注金額目標</label>
    <summarizedField>Opportunity.ST_Orderamounttarget__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.steel_OrderDate__c</field>
        <operation>greaterOrEqual</operation>
        <value>7/1/2025</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.steel_OrderDate__c</field>
        <operation>lessOrEqual</operation>
        <value>6/30/2026</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.RecordTypeId</field>
        <operation>equals</operation>
        <value>スチール_工事, ノハラスチール_工事_目標</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>内定, 受注ST, 仕掛, 完成</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CommonRecordType.recordType-meta.xml
<RecordType>
    <fullName>CommonRecordType</fullName>
    <active>true</active>
    <label>01.共通_得意先</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/ST_Estimatedamount__c.field-meta.xml
<CustomField>
    <fullName>ST_Estimatedamount__c</fullName>
    <label>受注金額ST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_grossprofit__c.field-meta.xml
<CustomField>
    <fullName>ST_grossprofit__c</fullName>
    <label>粗利</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_Orderamounttarget__c.field-meta.xml
<CustomField>
    <fullName>ST_Orderamounttarget__c</fullName>
    <label>受注金額目標</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_Orderquantitytarget__c.field-meta.xml
<CustomField>
    <fullName>ST_Orderquantitytarget__c</fullName>
    <label>受注数量目標</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_suryou__c.field-meta.xml
<CustomField>
    <fullName>ST_suryou__c</fullName>
    <label>数量(t)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_zyutyuararigaku__c.field-meta.xml
<CustomField>
    <fullName>ST_zyutyuararigaku__c</fullName>
    <label>目標利益額ST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/steel_OrderDate__c.field-meta.xml
<CustomField>
    <fullName>steel_OrderDate__c</fullName>
    <label>受注日_スチール</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/RecordType_Steel_sales.recordType-meta.xml
<RecordType>
    <fullName>RecordType_Steel_sales</fullName>
    <active>true</active>
    <businessProcess>ノハラスチール_棒鋼部</businessProcess>
    <label>スチール_材料販売</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/RecordType_SteelCons.recordType-meta.xml
<RecordType>
    <fullName>RecordType_SteelCons</fullName>
    <active>true</active>
    <businessProcess>野原スチール_工事部</businessProcess>
    <label>スチール_工事</label>
</RecordType>

force-app/main/default/classes/NHR_ST_EventSummaryBatchTest.cls
@isTest
public with sharing class NHR_ST_EventSummaryBatchTest {
    @isTest 
    static void test01() {
        createTestData();
        List<NHR_ST_EventSummaryCtrl.InputInfo> infos = new List<NHR_ST_EventSummaryCtrl.InputInfo>();
        NHR_ST_EventSummaryCtrl.InputInfo info = new NHR_ST_EventSummaryCtrl.InputInfo();
        info.StartDate = Date.today().addDays(-30);
        info.EndDate = Date.today();
        infos.add(info);

        NHR_ST_EventSummaryCtrl.NHR_ST_EventSummary(infos);

    }
    
    private static void createTestData(){
        // 共通取引先のレコードタイプを取得
        String ComAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CommonRecordType').getRecordTypeId();

        Account acc = new Account(Name = '株式会社A' , RecordTypeId = ComAccRecTypeId ,ST_Department__c = '事業一部', ST_focustype_kouji__c='積極', ST_focustype_boukoubu__c = '積極');
        Account acc1 = new Account(Name = '株式会社B' , RecordTypeId = ComAccRecTypeId ,ST_Department__c = '事業一部');
        insert new List<Account>{ acc, acc1 };

        Integer monthNow = Date.today().month();
        Integer startMonth = 0;
        if(monthNow >= 1 && monthNow <= 6){
            startMonth = 1;
        } else {
            startMonth = 8;
        }

        // 商談の「スチール_工事_材料販売_目標」レコードタイプを取得
        String opportunityRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('RecordType_SteelCons').getRecordTypeId();

        List<Opportunity> opportunities = new List<Opportunity>();
        Opportunity o1 = new Opportunity(Name = '株式会社A 事業一部目標',StageName = '受注',CloseDate = Date.newInstance(Date.today().year(), startMonth, 1),AccountId = acc.Id, ST_Orderamounttarget__c = 100, 
        ST_Orderquantitytarget__c = 100, ST_zyutyuararigaku__c = 100, steel_OrderDate__c = Date.newInstance(Date.today().year(), startMonth, 1), RecordTypeId = opportunityRecordTypeId);
        opportunities.add(o1);
        Opportunity o2 = new Opportunity(Name = '株式会社A 事業一部目標',StageName = '受注',CloseDate = Date.newInstance(Date.today().year(), startMonth + 1, 1),AccountId = acc.Id,ST_Orderamounttarget__c = 110, 
        ST_Orderquantitytarget__c = 110, ST_zyutyuararigaku__c = 110, steel_OrderDate__c = Date.newInstance(Date.today().year(), startMonth + 1, 1), RecordTypeId = opportunityRecordTypeId);
        opportunities.add(o2);

        Opportunity o3 = new Opportunity(Name = '株式会社B 事業一部目標',StageName = '受注',CloseDate = Date.newInstance(Date.today().year(), startMonth, 1),AccountId = acc1.Id, ST_Orderamounttarget__c = 100, 
        ST_Orderquantitytarget__c = 100, ST_zyutyuararigaku__c = 100, steel_OrderDate__c = Date.newInstance(Date.today().year(), startMonth, 1), RecordTypeId = opportunityRecordTypeId);
        opportunities.add(o3);
        Opportunity o4 = new Opportunity(Name = '株式会社B 事業一部目標',StageName = '受注',CloseDate = Date.newInstance(Date.today().year(), startMonth + 1, 1),AccountId = acc1.Id,ST_Orderamounttarget__c = 110, 
        ST_Orderquantitytarget__c = 110, ST_zyutyuararigaku__c = 110, steel_OrderDate__c = Date.newInstance(Date.today().year(), startMonth + 1, 1), RecordTypeId = opportunityRecordTypeId);
        opportunities.add(o4);

        String jisekiRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('RecordType_Steel_sales').getRecordTypeId();

        Opportunity o5 = new Opportunity(Name = '株式会社A 事業一部実績',StageName = '受注',CloseDate = Date.today(),AccountId = acc.Id, ST_Estimatedamount__c = 100, 
        ST_suryou__c = 100, ST_grossprofit__c = 100, steel_OrderDate__c = Date.newInstance(Date.today().year(), startMonth, 1), RecordTypeId = jisekiRecordTypeId);
        opportunities.add(o5);
        Opportunity o6 = new Opportunity(Name = '株式会社A 事業一部実績',StageName = '受注',CloseDate = Date.today(),AccountId = acc.Id, ST_Estimatedamount__c = 100, 
        ST_suryou__c = 100, ST_grossprofit__c = 100, steel_OrderDate__c = Date.newInstance(Date.today().year(), startMonth + 1, 1), RecordTypeId = jisekiRecordTypeId);
        opportunities.add(o6);

        Opportunity o7 = new Opportunity(Name = '株式会社B 事業1部実績',StageName = '受注',CloseDate = Date.today(),AccountId = acc1.Id, ST_Estimatedamount__c = 100, 
        ST_suryou__c = 100, ST_grossprofit__c = 100, steel_OrderDate__c = Date.newInstance(Date.today().year(), startMonth, 1), RecordTypeId = jisekiRecordTypeId);
        opportunities.add(o7);
        Opportunity o8 = new Opportunity(Name = '株式会社B 事業1部実績',StageName = '受注',CloseDate = Date.today(),AccountId = acc1.Id, ST_Estimatedamount__c = 100, 
        ST_suryou__c = 100, ST_grossprofit__c = 100, steel_OrderDate__c = Date.newInstance(Date.today().year(), startMonth + 1, 1), RecordTypeId = jisekiRecordTypeId);
        opportunities.add(o8);
        insert opportunities;
        
        Event eObj = new Event(EndDateTime = DateTime.now() , StartDateTime = DateTime.now(),Description='test',Subject='test',WhatId = opportunities[0].Id);
        insert eObj;
        
    }
}