force-app/main/default/objects/Account/fields/ST_focustype_kouji__c.field-meta.xml
<CustomField>
    <fullName>ST_focustype_kouji__c</fullName>
    <label>重点フラグ_工事</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>積極拡大</fullName>
            </value>
            <value>
                <fullName>重要な維持</fullName>
            </value>
            <value>
                <fullName>維持メンテ</fullName>
            </value>
            <value>
                <fullName>メンテ</fullName>
                <isActive>false</isActive>
                <label>メンテ</label>
            </value>
            <value>
                <fullName>放置</fullName>
                <isActive>false</isActive>
                <label>放置</label>
            </value>
            <value>
                <fullName>積極</fullName>
                <isActive>false</isActive>
                <label>積極</label>
            </value>
            <value>
                <fullName>維持</fullName>
                <isActive>false</isActive>
                <label>維持</label>
            </value>
            <value>
                <fullName>重要な維持①</fullName>
                <isActive>false</isActive>
                <label>重要な維持①</label>
            </value>
            <value>
                <fullName>重要な維持②</fullName>
                <isActive>false</isActive>
                <label>重要な維持②</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CommonRecordType.recordType-meta.xml
<RecordType>
    <fullName>CommonRecordType</fullName>
    <active>true</active>
    <label>01.共通_得意先</label>
</RecordType>

force-app/main/default/objects/Asset/fields/AdoptionAmount__c.field-meta.xml
<CustomField>
    <fullName>AdoptionAmount__c</fullName>
    <label>採用金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>原価</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/keiyakukoushinbi__c.field-meta.xml
<CustomField>
    <fullName>keiyakukoushinbi__c</fullName>
    <label>契約更新日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/ProductFamily__c.field-meta.xml
<CustomField>
    <fullName>ProductFamily__c</fullName>
    <label>商品カテゴリ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/syokaikeiyakubi__c.field-meta.xml
<CustomField>
    <fullName>syokaikeiyakubi__c</fullName>
    <label>初回契約日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/syukkabi__c.field-meta.xml
<CustomField>
    <fullName>syukkabi__c</fullName>
    <label>出荷日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Achievements.recordType-meta.xml
<RecordType>
    <fullName>Achievements</fullName>
    <active>true</active>
    <label>実績</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Target.recordType-meta.xml
<RecordType>
    <fullName>Target</fullName>
    <active>true</active>
    <label>目標</label>
</RecordType>

force-app/main/default/objects/Contact/fields/CW_ManagementTarget__c.field-meta.xml
<CustomField>
    <fullName>CW_ManagementTarget__c</fullName>
    <defaultValue>false</defaultValue>
    <label>管理対象_CW</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OrderBy__c.field-meta.xml
<CustomField>
    <fullName>OrderBy__c</fullName>
    <label>並び順</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/CommonRecordType.recordType-meta.xml
<RecordType>
    <fullName>CommonRecordType</fullName>
    <active>true</active>
    <label>共通_得意先担当者</label>
</RecordType>

force-app/main/default/objects/contact_schedule__c/contact_schedule__c.object-meta.xml
<CustomObject>
    <label>得意先担当者スケジュール</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>得意先担当者スケジュール名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/contact_schedule__c/fields/contactCS__c.field-meta.xml
<CustomField>
    <fullName>contactCS__c</fullName>
    <label>*得意先担当者</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>得意先担当者スケジュール</relationshipLabel>
    <relationshipName>coCS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/contact_schedule__c/fields/OrderBy__c.field-meta.xml
<CustomField>
    <fullName>OrderBy__c</fullName>
    <formula>IF(  YEAR(  TODAY()  )  = YEAR(  targetYear__c )  , 1 
			,IF(  (YEAR(  TODAY()  ) - 1)  = YEAR(  targetYear__c )  , 2 
			,0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>並び順</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/contact_schedule__c/fields/targetYear__c.field-meta.xml
<CustomField>
    <fullName>targetYear__c</fullName>
    <label>対象年(*日付)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/en_yojitsu__c.object-meta.xml
<CustomObject>
    <label>EN予実管理</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>予実管理番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/en_yojitsu__c/fields/en_ankenkubun_yozitsu__c.field-meta.xml
<CustomField>
    <fullName>en_ankenkubun_yozitsu__c</fullName>
    <label>案件区分</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/fields/en_juchu12__c.field-meta.xml
<CustomField>
    <fullName>en_juchu12__c</fullName>
    <label>受注金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/fields/en_jutyuarari__c.field-meta.xml
<CustomField>
    <fullName>en_jutyuarari__c</fullName>
    <label>受注粗利金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/fields/EN_kanseiki__c.field-meta.xml
<CustomField>
    <fullName>EN_kanseiki__c</fullName>
    <label>完成期</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/fields/en_koujihinsyu__c.field-meta.xml
<CustomField>
    <fullName>en_koujihinsyu__c</fullName>
    <label>工事品種</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/fields/en_kousyuy12__c.field-meta.xml
<CustomField>
    <fullName>en_kousyuy12__c</fullName>
    <label>目標受注金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/fields/EN_mokuhyouuriageararikingaku__c.field-meta.xml
<CustomField>
    <fullName>EN_mokuhyouuriageararikingaku__c</fullName>
    <label>目標売上粗利金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/fields/EN_mokuhyouuriagekingaku__c.field-meta.xml
<CustomField>
    <fullName>EN_mokuhyouuriagekingaku__c</fullName>
    <label>目標売上金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/fields/en_shodans__c.field-meta.xml
<CustomField>
    <fullName>en_shodans__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>商談</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>EN予実管理</relationshipLabel>
    <relationshipName>en_shodansan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/fields/en_tantobusyo1__c.field-meta.xml
<CustomField>
    <fullName>en_tantobusyo1__c</fullName>
    <label>担当部署</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/fields/en_tokuisaki_s__c.field-meta.xml
<CustomField>
    <fullName>en_tokuisaki_s__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>得意先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EN予実管理</relationshipLabel>
    <relationshipName>en_tokuisakis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/fields/en_uriagekingaku__c.field-meta.xml
<CustomField>
    <fullName>en_uriagekingaku__c</fullName>
    <label>売上金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/fields/En_uriara__c.field-meta.xml
<CustomField>
    <fullName>En_uriara__c</fullName>
    <label>売上粗利金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/fields/en_yojitu2__c.field-meta.xml
<CustomField>
    <fullName>en_yojitu2__c</fullName>
    <label>予実区分</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>予算</fullName>
            </value>
            <value>
                <fullName>実績</fullName>
                <default>true</default>
                <label>実績</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/fields/EN_yosan_arari__c.field-meta.xml
<CustomField>
    <fullName>EN_yosan_arari__c</fullName>
    <label>目標受注粗利金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/fields/Yeaemonth__c.field-meta.xml
<CustomField>
    <fullName>Yeaemonth__c</fullName>
    <label>年月</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/en_yojitsu__c/recordTypes/en_jissekin.recordType-meta.xml
<RecordType>
    <fullName>en_jissekin</fullName>
    <active>false</active>
    <label>EN実績入力</label>
</RecordType>

force-app/main/default/objects/en_yojitsu__c/recordTypes/en_yosan1.recordType-meta.xml
<RecordType>
    <fullName>en_yosan1</fullName>
    <active>true</active>
    <label>EN予算入力</label>
</RecordType>

force-app/main/default/objects/FormCreation__c/FormCreation__c.object-meta.xml
<CustomObject>
    <label>帳票作成用</label>
    <nameField>
        <label>帳票作成用名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FormCreation__c/fields/OrderBy__c.field-meta.xml
<CustomField>
    <fullName>OrderBy__c</fullName>
    <label>並び順</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <description>作成時の野原HD所有者の部署情報を表示</description>
    <label>担当部署</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/en_ankenkubun__c.field-meta.xml
<CustomField>
    <fullName>en_ankenkubun__c</fullName>
    <label>案件区分</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/EN_kanseiki__c.field-meta.xml
<CustomField>
    <fullName>EN_kanseiki__c</fullName>
    <label>完成期</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/en_koujihinsyu__c.field-meta.xml
<CustomField>
    <fullName>en_koujihinsyu__c</fullName>
    <label>工事品種</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/en_ukeoisyunkouyoteibi__c.field-meta.xml
<CustomField>
    <fullName>en_ukeoisyunkouyoteibi__c</fullName>
    <label>請負竣工予定日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/en_uriagekingaku__c.field-meta.xml
<CustomField>
    <fullName>en_uriagekingaku__c</fullName>
    <label>売上金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/en_zyutyuubi__c.field-meta.xml
<CustomField>
    <fullName>en_zyutyuubi__c</fullName>
    <label>受注日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/en_zyutyuukakudo__c.field-meta.xml
<CustomField>
    <fullName>en_zyutyuukakudo__c</fullName>
    <label>受注確度</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_DeliveryMonth__c.field-meta.xml
<CustomField>
    <fullName>ST_DeliveryMonth__c</fullName>
    <label>納入月</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_Orderquantitytarget__c.field-meta.xml
<CustomField>
    <fullName>ST_Orderquantitytarget__c</fullName>
    <label>受注数量目標</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_suryou__c.field-meta.xml
<CustomField>
    <fullName>ST_suryou__c</fullName>
    <label>数量(t)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/transtionDateToPhaseJuchuST__c.field-meta.xml
<CustomField>
    <fullName>transtionDateToPhaseJuchuST__c</fullName>
    <label>内定日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/en_zenekonsh.recordType-meta.xml
<RecordType>
    <fullName>en_zenekonsh</fullName>
    <active>true</active>
    <businessProcess>エンジゼネコン</businessProcess>
    <label>野原エンジニアリング【ゼネコン】</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/JU_sakzusekisanbpotaisyou.recordType-meta.xml
<RecordType>
    <fullName>JU_sakzusekisanbpotaisyou</fullName>
    <active>true</active>
    <businessProcess>住環境_作図積算BPO提案</businessProcess>
    <label>住環境_作図積算BPO提案</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/RecordType_Steel_kakou.recordType-meta.xml
<RecordType>
    <fullName>RecordType_Steel_kakou</fullName>
    <active>true</active>
    <businessProcess>野原スチール_工事部</businessProcess>
    <label>スチール_加工材販売</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/RecordType_SteelCons.recordType-meta.xml
<RecordType>
    <fullName>RecordType_SteelCons</fullName>
    <active>true</active>
    <businessProcess>野原スチール_工事部</businessProcess>
    <label>スチール_工事</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/RecordType_Steelzairyou_goal.recordType-meta.xml
<RecordType>
    <fullName>RecordType_Steelzairyou_goal</fullName>
    <active>true</active>
    <businessProcess>ノハラスチール_棒鋼部</businessProcess>
    <label>スチール_工事_材料販売_目標</label>
</RecordType>

force-app/main/default/objects/OrgManagement__c/OrgManagement__c.object-meta.xml
<CustomObject>
    <label>組織管理</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>組織管理名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgManagement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>得意先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>組織管理</relationshipLabel>
    <relationshipName>AccountOrg</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrgManagement__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>部署</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ST_Opportunity_Snapshot__c/ST_Opportunity_Snapshot__c.object-meta.xml
<CustomObject>
    <label>商談_スナップショット_ST</label>
    <nameField>
        <displayFormat>STO-{0000000000}</displayFormat>
        <label>商談_スナップショット_ST</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ST_Opportunity_Snapshot__c/fields/ST_focustype_kouji__c.field-meta.xml
<CustomField>
    <fullName>ST_focustype_kouji__c</fullName>
    <label>重点フラグ_工事</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Orderby__c.field-meta.xml
<CustomField>
    <fullName>Orderby__c</fullName>
    <label>並び順</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NHR_TestDataFactory.cls
@isTest
public without sharing class NHR_TestDataFactory {
    //取引先
    static List<Account> accs;
    public static List<Account> getAccount(){
        return accs;
    }

    //取引先担当者
    static List<Contact> cons;
    public static List<Contact> getContact(){
        return cons;
    }

     //商談
    static List<Opportunity> opps;
    public static List<Opportunity> getOpportunity(){
        return opps;
    }

    //EN予実管理
    static List<en_yojitsu__c > eys;
    public static List<en_yojitsu__c > getEn_yojitsu(){
        return eys;
    }

    //Excel出力用
    static List<FormCreation__c > cfcs;
    public static List<FormCreation__c > getFormCreation(){
        return cfcs;
    }
    
    //納入商品
    static List<Asset > asss;
    public static List<Asset> getAsset(){
        return asss;
    }
    
    //納品トン数
    static List<Steel_delivery__c> sds;
    public static List<Steel_delivery__c> getsds(){
        return sds;
    }
    
    //商談_スナップショット_ST 
    static List<ST_Opportunity_Snapshot__c> sos;
    public static List<ST_Opportunity_Snapshot__c> getsos(){
        return sos;
    }
    
    //組織管理
    static List<OrgManagement__c> org;
    public static List<OrgManagement__c> getOrg(){
        return org;
    }


    public static void createAllMstData() {
        // テスト用のユーザを作成
        Profile p = [
            SELECT Id
            FROM Profile
            WHERE Name='システム管理者'
        ];
        User u = new User(
            Alias = 'standt',
            Email='testing_ri_nhr@testorg.com',
            EmailEncodingKey='UTF-8',
            LastName='Testing_ri_nhr',
            LanguageLocaleKey='ja',
            LocaleSidKey='ja_JP',
            ProfileId = p.Id,
            TimeZoneSidKey='Asia/Tokyo',
            Department = '大阪営業部',
            UserName='testing_ri_nhr@testorg.com'
        );

        System.runAs(u) {
            //取引先
            accs = createAccount();

            //取引先担当者
            cons = createContact(accs);

            opps = createOpportunity(accs);

            eys = createEn_yojitsu(accs ,opps);

            cfcs = createFormCreation();
            
            asss = createAsset(accs[0],cons[0]);
            
            org = createOrg(accs[0]);
            
            sds = createSd();
            
            sos = createSos(accs);
        }
    }

    //取引先
    public static List<Account> createAccount() {
        // 共通取引先のレコードタイプを取得
        String recordtype_Com = 'CommonRecordType';
        String ComAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(recordtype_Com).getRecordTypeId();

        List<Account> insList = new List<Account>();
        insList.add(new Account(Name = '共通テスト' , RecordTypeId = ComAccRecTypeId ,ST_focustype_kouji__c = '積極拡大', CW_ManagementTarget__c=true));
        insList.add(new Account(Name = '共通テスト2' , RecordTypeId = ComAccRecTypeId ,ST_focustype_kouji__c = '積極'));
        insList.add(new Account(Name = '営繕工事_テスト' , RecordTypeId = ComAccRecTypeId ,ST_focustype_kouji__c = '積極'));
        insList.add(new Account(Name = '材料販売_テスト' , RecordTypeId = ComAccRecTypeId ,ST_focustype_kouji__c = '積極拡大'));

        insert insList;
        return insList;
    }

    //取引先責任者
    public static List<Contact> createContact(List<Account> accounts) {
        List<Contact> insList = new List<Contact>();
        insList.add(new Contact(LastName = '担当者1' , AccountId = accounts[0].Id,Department  = '部署1' , CW_ManagementTarget__c=true));
        insList.add(new Contact(LastName = '担当者2' , AccountId = accounts[0].Id,Department  = '部署1'));

        
        insert insList;
        
        contact_schedule__c csObj = new contact_schedule__c(contactCS__c =insList[0].Id , targetYear__c = Date.Today());
        insert csObj;
        return insList;
        
        
    }

    //商談
    public static List<Opportunity> createOpportunity(List<Account> accounts) {
        // 共通取引先のレコードタイプを取得
        String recordtype_Com = 'en_zenekonsh';
        String ComAccRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(recordtype_Com).getRecordTypeId();
        String JURecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('JU_sakzusekisanbpotaisyou').getRecordTypeId();
        String StId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('RecordType_SteelCons').getRecordTypeId();
        String StGoalId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('RecordType_Steelzairyou_goal').getRecordTypeId();
        String StId2 = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('RecordType_Steel_kakou').getRecordTypeId();


        List<Opportunity> insList = new List<Opportunity>();
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(-1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_koujihinsyu__c = NHR_Constant.CON1 ,en_zyutyuubi__c = Date.Today() ,AccountId = accounts[2].Id
                                    ,en_zyutyuukakudo__c = '受注' ,en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(-1)));
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(-1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_koujihinsyu__c = NHR_Constant.CON1 ,en_zyutyuubi__c = Date.Today() ,AccountId = accounts[3].Id
                                    ,en_zyutyuukakudo__c = '受注' ,en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(-1)));
        
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(-1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_koujihinsyu__c = NHR_Constant.CON1 ,en_zyutyuubi__c = Date.Today().addMonths(-1) ,AccountId = accounts[2].Id
                                    ,en_zyutyuukakudo__c = '受注' ,en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(-1)));
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(-1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_koujihinsyu__c = NHR_Constant.CON1 ,en_zyutyuubi__c = Date.Today().addMonths(-1) ,AccountId = accounts[3].Id
                                    ,en_zyutyuukakudo__c = '受注' ,en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(-1)));
        
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(-1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_koujihinsyu__c = NHR_Constant.CON1 ,en_zyutyuubi__c = Date.Today().addMonths(-2) ,AccountId = accounts[2].Id
                                    ,en_zyutyuukakudo__c = '受注' ,en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(-1)));
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(-1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_koujihinsyu__c = NHR_Constant.CON1 ,en_zyutyuubi__c = Date.Today().addMonths(-2) ,AccountId = accounts[3].Id
                                    ,en_zyutyuukakudo__c = '受注' ,en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(-1)));
        
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(-1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_koujihinsyu__c = NHR_Constant.CON1
                                    ,en_zyutyuukakudo__c = '受注' ,en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(-1)));
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today(),EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_koujihinsyu__c = NHR_Constant.CON1
                                    ,en_zyutyuukakudo__c = '受注' ,en_ukeoisyunkouyoteibi__c = Date.Today()));
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_koujihinsyu__c = NHR_Constant.CON1
                                    ,en_zyutyuukakudo__c = '受注' ,en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(1)));
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_koujihinsyu__c = NHR_Constant.CON2
                                    ,en_zyutyuukakudo__c = '受注' ,en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(2)));
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_koujihinsyu__c = NHR_Constant.CON3
                                    ,en_zyutyuukakudo__c = '受注' ,en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(3)));
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_koujihinsyu__c = NHR_Constant.CON1
                                    ,en_zyutyuukakudo__c = '受注' ,en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(4)));
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_koujihinsyu__c = NHR_Constant.CON2
                                    ,en_zyutyuukakudo__c = '受注' ,en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(5)));
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_koujihinsyu__c = NHR_Constant.CON3
                                    ,en_zyutyuukakudo__c = '受注' ,en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(6)));
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_zyutyuukakudo__c = '受注' ,en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(7)));
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_zyutyuukakudo__c = '受注' ,en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(8)));
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_zyutyuukakudo__c = '受注' ,en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(9)));

        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_koujihinsyu__c = NHR_Constant.CON1
                                    ,en_zyutyuukakudo__c = 'Aランク',en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(2)));
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_koujihinsyu__c = NHR_Constant.CON2
                                    ,en_zyutyuukakudo__c = 'Bランク',en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(2)));
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(1) ,EN_kanseiki__c = '13',Department__c='大阪営業部'
                                    ,en_koujihinsyu__c = NHR_Constant.CON3
                                    ,en_zyutyuukakudo__c = 'Cランク',en_ukeoisyunkouyoteibi__c = Date.Today().addMonths(2)));

                insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(1) ,EN_kanseiki__c = '14',Department__c='大阪営業部'
                                    ,en_zyutyuukakudo__c = '受注' ,en_ukeoisyunkouyoteibi__c = Date.Today().addYears(1)));

        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(1) ,EN_kanseiki__c = '14',Department__c='大阪営業部'
                                    ,en_zyutyuukakudo__c = 'Aランク',en_ukeoisyunkouyoteibi__c = Date.Today().addYears(1)));
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(1) ,EN_kanseiki__c = '14',Department__c='大阪営業部'
                                    ,en_zyutyuukakudo__c = 'Bランク',en_ukeoisyunkouyoteibi__c = Date.Today().addYears(1)));
        insList.add(new Opportunity(Name = '共通商談' , RecordTypeId = ComAccRecTypeId,StageName = '受注' ,en_ankenkubun__c = '本工事'
                                    ,CloseDate =  Date.Today().addMonths(1) ,EN_kanseiki__c = '14',Department__c='大阪営業部'
                                    ,en_zyutyuukakudo__c = 'Cランク',en_ukeoisyunkouyoteibi__c = Date.Today().addYears(1)));
        
        insList.add(new Opportunity(Name = 'JU商談' , RecordTypeId = JURecTypeId,StageName = '未着手' 
                                    ,CloseDate =  Date.Today().addMonths(1) ,Department__c='営業一部'));
        insList.add(new Opportunity(Name = 'JU商談' , RecordTypeId = JURecTypeId,StageName = '活動開始' 
                                    ,CloseDate =  Date.Today().addMonths(1) ,Department__c='営業一部'));
        insList.add(new Opportunity(Name = 'JU商談' , RecordTypeId = JURecTypeId,StageName = '初回訪問' 
                                    ,CloseDate =  Date.Today().addMonths(1) ,Department__c='営業一部'));
        insList.add(new Opportunity(Name = 'JU商談' , RecordTypeId = JURecTypeId,StageName = 'KMプレゼン完了' 
                                    ,CloseDate =  Date.Today().addMonths(1) ,Department__c='営業一部'));
        insList.add(new Opportunity(Name = 'JU商談' , RecordTypeId = JURecTypeId,StageName = 'Phase1導入' 
                                    ,CloseDate =  Date.Today().addMonths(1) ,Department__c='営業一部'));
        insList.add(new Opportunity(Name = 'JU商談' , RecordTypeId = JURecTypeId,StageName = '最終提案完了' 
                                    ,CloseDate =  Date.Today().addMonths(1) ,Department__c='営業一部'));
        insList.add(new Opportunity(Name = 'JU商談' , RecordTypeId = JURecTypeId,StageName = '検討保留' 
                                    ,CloseDate =  Date.Today().addMonths(1) ,Department__c='営業一部'));
        insList.add(new Opportunity(Name = 'JU商談' , RecordTypeId = JURecTypeId,StageName = '提案停止' 
                                    ,CloseDate =  Date.Today().addMonths(1) ,Department__c='営業一部'));
        insList.add(new Opportunity(Name = 'JU商談' , RecordTypeId = JURecTypeId,StageName = '採用（受注）' 
                                    ,CloseDate =  Date.Today().addMonths(1) ,Department__c='営業一部'));
        insList.add(new Opportunity(Name = 'JU商談' , RecordTypeId = JURecTypeId,StageName = '在阪切替' 
                                    ,CloseDate =  Date.Today().addMonths(1) ,Department__c='営業一部'));
        
        insList.add(new Opportunity(Name = 'ST商談' , RecordTypeId = StId,StageName = 'A' ,transtionDateToPhaseJuchuST__c =  Date.Today().addMonths(1)
                                    ,CloseDate =  Date.Today().addMonths(1) , ST_suryou__c = 10 ));
        insList.add(new Opportunity(Name = 'ST商談' , RecordTypeId = StId,StageName = 'A' ,transtionDateToPhaseJuchuST__c =  Date.Today().addMonths(2)
                                    ,CloseDate =  Date.Today().addMonths(1) , ST_suryou__c = 60 ));
        insList.add(new Opportunity(Name = 'ST商談' , RecordTypeId = StId,StageName = 'A' ,transtionDateToPhaseJuchuST__c =  Date.Today().addMonths(3)
                                    ,CloseDate =  Date.Today().addMonths(1) , ST_suryou__c = 300 ));
        insList.add(new Opportunity(Name = 'ST商談' , RecordTypeId = StId,StageName = 'A' ,transtionDateToPhaseJuchuST__c =  Date.Today().addMonths(4)
                                    ,CloseDate =  Date.Today().addMonths(1) , ST_suryou__c = 800 ));
        insList.add(new Opportunity(Name = 'ST商談' , RecordTypeId = StId,StageName = 'A' ,transtionDateToPhaseJuchuST__c =  Date.Today().addMonths(5)
                                    ,CloseDate =  Date.Today().addMonths(1) , ST_suryou__c = 1700 ));
        
        insList.add(new Opportunity(Name = 'ST商談' , RecordTypeId = StId,StageName = '受注ST' ,transtionDateToPhaseJuchuST__c =  Date.Today().addMonths(6)
                                    ,CloseDate =  Date.Today().addMonths(1) , ST_suryou__c = 10 ));
        insList.add(new Opportunity(Name = 'ST商談' , RecordTypeId = StId,StageName = '受注ST' ,transtionDateToPhaseJuchuST__c =  Date.Today().addMonths(7)
                                    ,CloseDate =  Date.Today().addMonths(1) , ST_suryou__c = 60 ));
        insList.add(new Opportunity(Name = 'ST商談' , RecordTypeId = StId,StageName = '受注ST' ,transtionDateToPhaseJuchuST__c =  Date.Today().addMonths(8)
                                    ,CloseDate =  Date.Today().addMonths(1) , ST_suryou__c = 300 ));
        insList.add(new Opportunity(Name = 'ST商談' , RecordTypeId = StId,StageName = '受注ST' ,transtionDateToPhaseJuchuST__c =  Date.Today().addMonths(9)
                                    ,CloseDate =  Date.Today().addMonths(1) , ST_suryou__c = 800 ));
        insList.add(new Opportunity(Name = 'ST商談' , RecordTypeId = StId,StageName = '受注ST' ,transtionDateToPhaseJuchuST__c =  Date.Today().addMonths(10)
                                    ,CloseDate =  Date.Today().addMonths(1) , ST_suryou__c = 1700 ));
        
        insList.add(new Opportunity(Name = 'ST商談' , RecordTypeId = StId,StageName = '仕掛' 
                                    ,CloseDate =  Date.Today().addMonths(1) , ST_suryou__c = 10 ));
        insList.add(new Opportunity(Name = 'ST商談' , RecordTypeId = StId,StageName = '仕掛' 
                                    ,CloseDate =  Date.Today().addMonths(1) , ST_suryou__c = 60 ));
        insList.add(new Opportunity(Name = 'ST商談' , RecordTypeId = StId,StageName = '仕掛' 
                                    ,CloseDate =  Date.Today().addMonths(1) , ST_suryou__c = 300 ));
        insList.add(new Opportunity(Name = 'ST商談' , RecordTypeId = StId,StageName = '仕掛' 
                                    ,CloseDate =  Date.Today().addMonths(1) , ST_suryou__c = 800 ));
        insList.add(new Opportunity(Name = 'ST商談' , RecordTypeId = StId,StageName = '仕掛' 
                                    ,CloseDate =  Date.Today().addMonths(1) , ST_suryou__c = 1700 ));
        
        insList.add(new Opportunity(Name = 'ST商談2' , RecordTypeId = StId2,StageName = '仕掛' ,ST_DeliveryMonth__c = Date.Today()
                                    ,CloseDate =  Date.Today().addMonths(1) , ST_suryou__c = 1700 ));
        
        insList.add(new Opportunity(Name = 'ST商談目標' , RecordTypeId = StGoalId,StageName = '受注' ,AccountId = accounts[0].Id
                                    ,CloseDate =  Date.Today().addMonths(-1) , ST_Orderquantitytarget__c = 10 ));
        insList.add(new Opportunity(Name = 'ST商談目標' , RecordTypeId = StGoalId,StageName = '受注' ,AccountId = accounts[0].Id
                                    ,CloseDate =  Date.Today() , ST_Orderquantitytarget__c = 10 ));
        insList.add(new Opportunity(Name = 'ST商談目標' , RecordTypeId = StGoalId,StageName = '受注' ,AccountId = accounts[0].Id
                                    ,CloseDate =  Date.Today().addMonths(1) , ST_Orderquantitytarget__c = 10 ));
        insList.add(new Opportunity(Name = 'ST商談目標' , RecordTypeId = StGoalId,StageName = '受注' ,AccountId = accounts[0].Id
                                    ,CloseDate =  Date.Today().addMonths(2) , ST_Orderquantitytarget__c = 10 ));
        insList.add(new Opportunity(Name = 'ST商談目標' , RecordTypeId = StGoalId,StageName = '受注' ,AccountId = accounts[1].Id
                                    ,CloseDate =  Date.Today().addMonths(3) , ST_Orderquantitytarget__c = 10 ));
        insList.add(new Opportunity(Name = 'ST商談目標' , RecordTypeId = StGoalId,StageName = '受注' ,AccountId = accounts[1].Id
                                    ,CloseDate =  Date.Today().addMonths(4) , ST_Orderquantitytarget__c = 10 ));
        insert insList;
        return insList;
    }

    //EN予実管理
    public static List<en_yojitsu__c> createEn_yojitsu(List<Account> accounts ,List<Opportunity> opps) {
        // 共通取引先のレコードタイプを取得
        String recordtype_Com1 = 'en_yosan1';
        String recordtype_Com2 = 'en_jissekin';
        String ComAccRecTypeId1 = Schema.SObjectType.en_yojitsu__c.getRecordTypeInfosByDeveloperName().get(recordtype_Com1).getRecordTypeId();
        String ComAccRecTypeId2 = Schema.SObjectType.en_yojitsu__c.getRecordTypeInfosByDeveloperName().get(recordtype_Com2).getRecordTypeId();

        List<en_yojitsu__c> insList = new List<en_yojitsu__c>();
        insList.add(setEn_yojitsu(ComAccRecTypeId1 ,Date.Today().addMonths(-1) ,' 予算',accounts ,opps) );
        insList.add(setEn_yojitsu(ComAccRecTypeId1 ,Date.Today() ,' 予算',accounts ,opps));
        insList.add(setEn_yojitsu(ComAccRecTypeId1 ,Date.Today().addMonths(1) ,' 予算',accounts ,opps));
        insList.add(setEn_yojitsu(ComAccRecTypeId1 ,Date.Today().addYears(-1) ,' 予算',accounts ,opps));
        insList.add(setEn_yojitsu(ComAccRecTypeId1 ,Date.Today().addYears(1) ,' 予算',accounts ,opps));
        insList.add(setEn_yojitsu(ComAccRecTypeId1 ,Date.Today().addYears(2) ,' 予算',accounts ,opps));

        insList.add(setEn_yojitsu(ComAccRecTypeId1 ,Date.Today().addMonths(-1) ,' 実績',accounts ,opps));
        insList.add(setEn_yojitsu(ComAccRecTypeId1 ,Date.Today() ,' 実績',accounts ,opps));
        insList.add(setEn_yojitsu(ComAccRecTypeId1 ,Date.Today().addMonths(1)  ,' 実績',accounts ,opps));
        insList.add(setEn_yojitsu(ComAccRecTypeId1 ,Date.Today().addYears(-1)  ,' 実績',accounts ,opps));
        insList.add(setEn_yojitsu(ComAccRecTypeId1 ,Date.Today().addYears(1)  ,' 実績',accounts ,opps));
        insList.add(setEn_yojitsu(ComAccRecTypeId1 ,Date.Today().addYears(2)  ,' 実績',accounts ,opps));

        insert insList;
        return insList;
    }

     //EN予実管理
    public static en_yojitsu__c setEn_yojitsu(String recordTypeId , Date inDate , String yojitu ,List<Account> accounts ,List<Opportunity> opps) {
        en_yojitsu__c obj = new en_yojitsu__c();
        obj.en_uriagekingaku__c = 0;
        obj.En_uriara__c =  0;
        obj.en_juchu12__c =  0;
        obj.en_jutyuarari__c =  0;
        obj.EN_mokuhyouuriagekingaku__c =  0;
        obj.EN_mokuhyouuriageararikingaku__c =  0;
        obj.en_kousyuy12__c =  0;
        obj.EN_yosan_arari__c =  0;
        obj.Yeaemonth__c = inDate;
        obj.en_yojitu2__c = yojitu ;
        obj.recordTypeId = recordTypeId;
         obj.en_shodans__c = opps[0].id;
         obj.en_tokuisaki_s__c = accounts[0].id;
        obj.en_tantobusyo1__c = '大阪営業部';
        obj.en_ankenkubun_yozitsu__c = '本工事';
        if (Date.Today().month() < 7) {
             obj.EN_kanseiki__c = String.valueOf(Date.Today().Year() -2024 + 12);
        } else {
            obj.EN_kanseiki__c = String.valueOf(Date.Today().Year() -2024 + 12 + 1);
        }
       
        return obj;
    }

    //EN予実管理
    public static List<FormCreation__c> createFormCreation() {
        List<FormCreation__c> insList = new List<FormCreation__c>();
        insList.add(new FormCreation__c(Name = 'Sales1_1' , OrderBy__c = 1));
        insList.add(new FormCreation__c(Name = 'Sales1_2' , OrderBy__c = 1));
        insList.add(new FormCreation__c(Name = 'Sales2' , OrderBy__c = 1));
        insList.add(new FormCreation__c(Name = 'Sales3' , OrderBy__c = 1));
        insList.add(new FormCreation__c(Name = 'Sales4' , OrderBy__c = 1));

        insList.add(new FormCreation__c(Name = NHR_Constant.BATCHNAME_AOT , OrderBy__c = 1));
        insList.add(new FormCreation__c(Name = NHR_Constant.BATCHNAME_AST , OrderBy__c = 1));
        insList.add(new FormCreation__c(Name = NHR_Constant.BATCHNAME_CO , OrderBy__c = 1));
        insList.add(new FormCreation__c(Name = NHR_Constant.BATCHNAME_COO , OrderBy__c = 1));
        insList.add(new FormCreation__c(Name = NHR_Constant.BATCHNAME_SRM1 , OrderBy__c = 1));
        insList.add(new FormCreation__c(Name = NHR_Constant.BATCHNAME_SRM2 , OrderBy__c = 1));
        insList.add(new FormCreation__c(Name = NHR_Constant.BATCHNAME_SRM3 , OrderBy__c = 1));
        insList.add(new FormCreation__c(Name = NHR_Constant.BATCHNAME_OAL , OrderBy__c = 1));
        insList.add(new FormCreation__c(Name = NHR_Constant.BATCHNAME_OAL , OrderBy__c = 2));

        insert insList;
        return insList;
    }


    //納入商品
    public static List<Asset> createAsset(Account acc ,contact con) {
        // レコードタイプを取得
        String Ach = 'Achievements';
        String AchRecTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get(Ach).getRecordTypeId();
        String Tar = 'Target';
        String TarRecTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get(Tar).getRecordTypeId();

        List<Asset> insList = new List<Asset>();
        insList.add(new Asset(Name = '納入商品1' , RecordTypeId = AchRecTypeId , AdoptionAmount__c = 10000,Cost__c=6000,Price  = 10000,
                             ProductFamily__c = 'Pro3AK',syokaikeiyakubi__c = Date.today(), syukkabi__c = Date.today().addMonths(1), AccountId= acc.id ,ContactId =con.id));
        insList.add(new Asset(Name = '納入商品2' , RecordTypeId = AchRecTypeId , AdoptionAmount__c = 10000,Cost__c=6000,Price  = 10000,
                             ProductFamily__c = 'Pro2',syokaikeiyakubi__c = Date.today(), syukkabi__c = Date.today().addMonths(2), AccountId= acc.id ,ContactId =con.id));
        insList.add(new Asset(Name = '納入商品3' , RecordTypeId = AchRecTypeId , AdoptionAmount__c = 10000,Cost__c=6000,Price  = 10000,
                             ProductFamily__c = 'Pro2備品',syokaikeiyakubi__c = Date.today(), syukkabi__c = Date.today().addMonths(3), AccountId= acc.id ,ContactId =con.id));
        insList.add(new Asset(Name = '納入商品4' , RecordTypeId = AchRecTypeId , AdoptionAmount__c = 10000,Cost__c=6000,Price  = 10000,
                             ProductFamily__c = 'Axis',syokaikeiyakubi__c = Date.today(), syukkabi__c = Date.today().addMonths(4), AccountId= acc.id ,ContactId =con.id));
        insList.add(new Asset(Name = '納入商品5' , RecordTypeId = AchRecTypeId , AdoptionAmount__c = 10000,Cost__c=6000,Price  = 10000,
                             ProductFamily__c = 'SaaS',syokaikeiyakubi__c = Date.today(), syukkabi__c = Date.today().addMonths(5), AccountId= acc.id ,ContactId =con.id));
        insList.add(new Asset(Name = '納入商品6' , RecordTypeId = AchRecTypeId , AdoptionAmount__c = 10000,Cost__c=6000,Price  = 10000,
                             ProductFamily__c = 'SaaS',syokaikeiyakubi__c = Date.today(), syukkabi__c = Date.today().addMonths(6) ,keiyakukoushinbi__c = Date.today().addYears(1), AccountId= acc.id ,ContactId =con.id));

        insList.add(new Asset(Name = '納入商品2_1' , RecordTypeId = TarRecTypeId , AdoptionAmount__c = 10000,Cost__c=6000,Price  = 10000,
                             ProductFamily__c = 'Pro3AK',syokaikeiyakubi__c = Date.today(), syukkabi__c = Date.today().addMonths(1), AccountId= acc.id ,ContactId =con.id));
        insList.add(new Asset(Name = '納入商品2_2' , RecordTypeId = TarRecTypeId , AdoptionAmount__c = 10000,Cost__c=6000,Price  = 10000,
                             ProductFamily__c = 'Pro2',syokaikeiyakubi__c = Date.today(), syukkabi__c = Date.today().addMonths(2), AccountId= acc.id ,ContactId =con.id));
        insList.add(new Asset(Name = '納入商品2_3' , RecordTypeId = TarRecTypeId , AdoptionAmount__c = 10000,Cost__c=6000,Price  = 10000,
                              ProductFamily__c = 'Axis',syokaikeiyakubi__c = Date.today(), syukkabi__c = Date.today().addMonths(3), AccountId= acc.id ,ContactId =con.id));
        insList.add(new Asset(Name = '納入商品2_4' , RecordTypeId = TarRecTypeId , AdoptionAmount__c = 10000,Cost__c=6000,Price  = 10000,
                              ProductFamily__c = 'Axis',syokaikeiyakubi__c = Date.today(), syukkabi__c = Date.today().addMonths(4), AccountId= acc.id ,ContactId =con.id));
        insList.add(new Asset(Name = '納入商品2_5' , RecordTypeId = TarRecTypeId , AdoptionAmount__c = 10000,Cost__c=6000,Price  = 10000,
                              ProductFamily__c = 'Axis',syokaikeiyakubi__c = Date.today(), syukkabi__c = Date.today().addMonths(5), AccountId= acc.id ,ContactId =con.id));
        insList.add(new Asset(Name = '納入商品2_6' , RecordTypeId = TarRecTypeId , AdoptionAmount__c = 10000,Cost__c=6000,Price  = 10000,
                              ProductFamily__c = 'Axis',syokaikeiyakubi__c = Date.today(), syukkabi__c = Date.today().addMonths(6), AccountId= acc.id ,ContactId =con.id));
        insList.add(new Asset(Name = '納入商品2_7' , RecordTypeId = TarRecTypeId , AdoptionAmount__c = 10000,Cost__c=6000,Price  = 10000,
                              ProductFamily__c = 'Axis',syokaikeiyakubi__c = Date.today(), syukkabi__c = Date.today().addMonths(7), AccountId= acc.id ,ContactId =con.id));
        insList.add(new Asset(Name = '納入商品2_8' , RecordTypeId = TarRecTypeId , AdoptionAmount__c = 10000,Cost__c=6000,Price  = 10000,
                              ProductFamily__c = 'Axis',syokaikeiyakubi__c = Date.today(), syukkabi__c = Date.today().addMonths(8), AccountId= acc.id ,ContactId =con.id));
        insList.add(new Asset(Name = '納入商品2_9' , RecordTypeId = TarRecTypeId , AdoptionAmount__c = 10000,Cost__c=6000,Price  = 10000,
                              ProductFamily__c = 'Axis',syokaikeiyakubi__c = Date.today(), syukkabi__c = Date.today().addMonths(9), AccountId= acc.id ,ContactId =con.id));
        insert insList;
        return insList;
    }
    
    //取引先
    public static List<OrgManagement__c > createOrg(Account acc) {
        List<OrgManagement__c> insList = new List<OrgManagement__c>();
        insList.add(new OrgManagement__c(Account__c = acc.id, Department__c  = '部署1',OrderBy__c =1));

        insert insList;
        return insList;
    }
    
    //納品トン数
    public static List<Steel_delivery__c > createSd() {
        List<Steel_delivery__c> insList = new List<Steel_delivery__c>();
        List<Opportunity> oppObj = [ Select Id From Opportunity
        WHERE RecordType.DeveloperName = 'RecordType_SteelCons' Limit 1];
        
        List<Opportunity> oppObj2 = [ Select Id From Opportunity
        WHERE RecordType.DeveloperName = 'RecordType_Steel_kakou' Limit 1];
        
        insList.add(New Steel_delivery__c(Opp__c = oppObj[0].Id));
        insList.add(New Steel_delivery__c(Opp__c = oppObj2[0].Id));
        
        
        insert insList;
        return insList;
    }


    //商談_スナップショット_ST
    public static List<ST_Opportunity_Snapshot__c> createSos(List<Account> accounts ) {

        List<ST_Opportunity_Snapshot__c> insList = new List<ST_Opportunity_Snapshot__c>();
        insList.add(new ST_Opportunity_Snapshot__c(AccountId__c = accounts[0].id, Department__c  = '事業1部' ,StageName__c = 'A',ST_focustype_kouji__c = '積極拡大' , ST_yosankumikomi__c = '2025年6月期'));
        insList.add(new ST_Opportunity_Snapshot__c(AccountId__c = accounts[0].id, Department__c  = '事業2部',StageName__c = 'C',ST_focustype_kouji__c = '積極拡大' , ST_yosankumikomi__c = '2025年6月期'));
        insList.add(new ST_Opportunity_Snapshot__c(AccountId__c = accounts[1].id, Department__c  = '事業1部',StageName__c = 'E',ST_focustype_kouji__c = '積極' , ST_yosankumikomi__c = '2025年6月期'));
        insList.add(new ST_Opportunity_Snapshot__c(AccountId__c = accounts[1].id, Department__c  = '事業2部',StageName__c = 'G',ST_focustype_kouji__c = '積極' , ST_yosankumikomi__c = '2025年6月期'));

        insert insList;
        return insList;
    }

}