force-app/main/default/objects/Account/fields/ST_Orderamounttarget__c.field-meta.xml
<CustomField>
    <fullName>ST_Orderamounttarget__c</fullName>
    <label>受注金額目標</label>
    <summarizedField>Opportunity.ST_Orderamounttarget__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.steel_OrderDate__c</field>
        <operation>greaterOrEqual</operation>
        <value>7/1/2025</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.steel_OrderDate__c</field>
        <operation>lessOrEqual</operation>
        <value>6/30/2026</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.RecordTypeId</field>
        <operation>equals</operation>
        <value>スチール_工事, ノハラスチール_工事_目標</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>内定, 受注ST, 仕掛, 完成</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CommonRecordType.recordType-meta.xml
<RecordType>
    <fullName>CommonRecordType</fullName>
    <active>true</active>
    <label>01.共通_得意先</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Jukankyo.recordType-meta.xml
<RecordType>
    <fullName>Jukankyo</fullName>
    <active>true</active>
    <label>住環境</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/ST_Orderamounttarget__c.field-meta.xml
<CustomField>
    <fullName>ST_Orderamounttarget__c</fullName>
    <label>受注金額目標</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_Orderquantitytarget__c.field-meta.xml
<CustomField>
    <fullName>ST_Orderquantitytarget__c</fullName>
    <label>受注数量目標</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_zyutyuararigaku__c.field-meta.xml
<CustomField>
    <fullName>ST_zyutyuararigaku__c</fullName>
    <label>目標利益額ST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Jukankyo.recordType-meta.xml
<RecordType>
    <fullName>Jukankyo</fullName>
    <active>true</active>
    <businessProcess>住環境</businessProcess>
    <label>住環境</label>
</RecordType>

force-app/main/default/classes/ContentDocumentLinkTriggerHandlerTest.cls
@isTest
public with sharing class ContentDocumentLinkTriggerHandlerTest {
    @isTest
    static void test(){
        String cdlId =  createData();

        Map<Id, ContentDocumentLink> newMap = new Map<Id, ContentDocumentLink>([SELECT Id, LinkedEntityId FROM ContentDocumentLink WHERE Id = :cdlId]);
        ContentDocumentLinkTriggerHandler handler = new ContentDocumentLinkTriggerHandler();
        handler.handleAfterInsert(newMap);
    }

    public static String createData(){
        // 共通取引先のレコードタイプを取得
        String ComAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CommonRecordType').getRecordTypeId();
        Account acc = new Account(Name = '株式会社A' , RecordTypeId = ComAccRecTypeId ,ST_Department__c = '事業一部');
        insert acc;

        ContentVersion conObject = new ContentVersion();
        conObject.title = '見積.xls';
        conObject.PathOnClient = '見積.xls';
        conObject.versiondata=Blob.valueOf('Test Content Data');
        insert conObject;

        String opportunityRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Jukankyo').getRecordTypeId();
        Opportunity o1 = new Opportunity(Name = '株式会社B 事業1部目標',StageName = '受注',AccountId = acc.Id, ST_Orderamounttarget__c = 100, 
        ST_Orderquantitytarget__c = 100, ST_zyutyuararigaku__c = 100, CloseDate = Date.newInstance(Date.today().year(), 1, 1), RecordTypeId = opportunityRecordTypeId);
        insert o1;

        ContentVersion cv = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :conObject.Id];
        ContentDocumentLink cdl = new ContentDocumentLink(ContentDocumentId = cv.ContentDocumentId, LinkedEntityId = o1.Id, ShareType = 'V', Visibility = 'AllUsers');
        insert cdl;

        return cdl.Id;
    }
}