force-app/main/default/objects/Account/fields/ST_Orderamounttarget__c.field-meta.xml
<CustomField>
    <fullName>ST_Orderamounttarget__c</fullName>
    <label>受注金額目標</label>
    <summarizedField>Opportunity.ST_Orderamounttarget__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.steel_OrderDate__c</field>
        <operation>greaterOrEqual</operation>
        <value>7/1/2025</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.steel_OrderDate__c</field>
        <operation>lessOrEqual</operation>
        <value>6/30/2026</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.RecordTypeId</field>
        <operation>equals</operation>
        <value>スチール_工事, ノハラスチール_工事_目標</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>内定, 受注ST, 仕掛, 完成</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CommonRecordType.recordType-meta.xml
<RecordType>
    <fullName>CommonRecordType</fullName>
    <active>true</active>
    <label>01.共通_得意先</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/ST_Estimatedamount__c.field-meta.xml
<CustomField>
    <fullName>ST_Estimatedamount__c</fullName>
    <label>受注金額ST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_grossprofit__c.field-meta.xml
<CustomField>
    <fullName>ST_grossprofit__c</fullName>
    <label>粗利</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_Orderamounttarget__c.field-meta.xml
<CustomField>
    <fullName>ST_Orderamounttarget__c</fullName>
    <label>受注金額目標</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_Orderquantitytarget__c.field-meta.xml
<CustomField>
    <fullName>ST_Orderquantitytarget__c</fullName>
    <label>受注数量目標</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_suryou__c.field-meta.xml
<CustomField>
    <fullName>ST_suryou__c</fullName>
    <label>数量(t)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_zyutyuararigaku__c.field-meta.xml
<CustomField>
    <fullName>ST_zyutyuararigaku__c</fullName>
    <label>目標利益額ST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/steel_OrderDate__c.field-meta.xml
<CustomField>
    <fullName>steel_OrderDate__c</fullName>
    <label>受注日_スチール</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/RecordType_Steel_sales.recordType-meta.xml
<RecordType>
    <fullName>RecordType_Steel_sales</fullName>
    <active>true</active>
    <businessProcess>ノハラスチール_棒鋼部</businessProcess>
    <label>スチール_材料販売</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/RecordType_Steelzairyou_goal.recordType-meta.xml
<RecordType>
    <fullName>RecordType_Steelzairyou_goal</fullName>
    <active>true</active>
    <businessProcess>ノハラスチール_棒鋼部</businessProcess>
    <label>スチール_工事_材料販売_目標</label>
</RecordType>

force-app/main/default/classes/NHR_ST_CusOrderAmountQuantityBatchTest.cls
@isTest 
public with sharing class NHR_ST_CusOrderAmountQuantityBatchTest {
    @isTest 
    static void test01() {
        createTestData();

        Database.executeBatch(new NHR_ST_CusOrderAmountQuantityBatch(), 200);
        NHR_ST_CusOrderAmountQuantityBatch.forTest();
    }

    private static void createTestData(){
        // 共通取引先のレコードタイプを取得
        String ComAccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CommonRecordType').getRecordTypeId();

        Account acc = new Account(Name = '株式会社A' , RecordTypeId = ComAccRecTypeId ,ST_Department__c = '事業一部');
        insert acc;

        Integer monthNow = Date.today().month();
        Integer startMonth = 0;
        if(monthNow >= 1 && monthNow <= 6){
            startMonth = 1;
        } else {
            startMonth = 8;
        }

        // 商談の「スチール_工事_材料販売_目標」レコードタイプを取得
        String opportunityRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('RecordType_Steelzairyou_goal').getRecordTypeId();

        List<Opportunity> opportunities = new List<Opportunity>();
        Opportunity o1 = new Opportunity(Name = '株式会社B 事業1部目標',StageName = '受注',AccountId = acc.Id, ST_Orderamounttarget__c = 100, 
        ST_Orderquantitytarget__c = 100, ST_zyutyuararigaku__c = 100, CloseDate = Date.newInstance(Date.today().year(), startMonth, 1), RecordTypeId = opportunityRecordTypeId);
        opportunities.add(o1);

        Opportunity o2 = new Opportunity(Name = '株式会社B 事業1部目標',StageName = '受注',AccountId = acc.Id,ST_Orderamounttarget__c = 110, 
        ST_Orderquantitytarget__c = 110, ST_zyutyuararigaku__c = 110, CloseDate = Date.newInstance(Date.today().year(), startMonth + 1, 1), RecordTypeId = opportunityRecordTypeId);
        opportunities.add(o2);

        Opportunity o3 = new Opportunity(Name = '株式会社B 事業1部実績',StageName = '受注',AccountId = acc.Id, ST_Estimatedamount__c = 100, 
        ST_suryou__c = 100, ST_grossprofit__c = 100, steel_OrderDate__c = Date.newInstance(Date.today().year(), startMonth, 1), CloseDate = Date.newInstance(Date.today().year(), startMonth, 1), 
        RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('RecordType_Steel_sales').getRecordTypeId());
        opportunities.add(o3);

        Opportunity o4 = new Opportunity(Name = '株式会社B 事業1部実績',StageName = '受注',AccountId = acc.Id, ST_Estimatedamount__c = 100, 
        ST_suryou__c = 100, ST_grossprofit__c = 100, steel_OrderDate__c = Date.newInstance(Date.today().year(), startMonth + 1, 1),CloseDate = Date.newInstance(Date.today().year(), startMonth + 1, 1),  
        RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('RecordType_Steel_sales').getRecordTypeId());
        opportunities.add(o4);
        insert opportunities;
    }
}