force-app/main/default/objects/Opportunity/fields/Last2WeekActive__c.field-meta.xml
<CustomField>
    <fullName>Last2WeekActive__c</fullName>
    <label>前々回の活動</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LastWeekActive__c.field-meta.xml
<CustomField>
    <fullName>LastWeekActive__c</fullName>
    <label>前回の活動</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ThisWeekActive__c.field-meta.xml
<CustomField>
    <fullName>ThisWeekActive__c</fullName>
    <label>今回の活動</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/RecordType_Steel_sales.recordType-meta.xml
<RecordType>
    <fullName>RecordType_Steel_sales</fullName>
    <active>true</active>
    <businessProcess>ノハラスチール_棒鋼部</businessProcess>
    <label>スチール_材料販売</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/RecordType_SteelCons.recordType-meta.xml
<RecordType>
    <fullName>RecordType_SteelCons</fullName>
    <active>true</active>
    <businessProcess>野原スチール_工事部</businessProcess>
    <label>スチール_工事</label>
</RecordType>

force-app/main/default/classes/NHR_ST_ActivityChangeBatch.cls
/*
 * 【ST】今週の活動・先週の活動・先々週の活動は週毎に自動変更
 */
global without sharing class NHR_ST_ActivityChangeBatch implements Database.Batchable<sObject>, Database.Stateful{
   
    global NHR_ST_ActivityChangeBatch(){}

    //データ取得
    global Database.QueryLocator start(Database.BatchableContext BC){
        system.debug('NHR_ST_ActivityChangeBatch');
    	String query = getSoql();
        return Database.getQueryLocator(query);
    }

    //開始
    global void execute(Database.BatchableContext BC, List<Opportunity> scopes){

        for(Opportunity obj : scopes) {
            obj.Last2WeekActive__c = obj.LastWeekActive__c;
            obj.LastWeekActive__c = obj.ThisWeekActive__c;
            obj.ThisWeekActive__c = '';
        }
        
        update scopes;
    }

     //完了
    global void finish(Database.BatchableContext BC){}
    
    global static String getSoql(){
        String soql = '';
        soql += ' SELECT ';
        soql += ' Id';
        soql += ' ,ThisWeekActive__c ';
        soql += ' ,LastWeekActive__c ';
        soql += ' ,Last2WeekActive__c ';
        soql += ' FROM Opportunity  ';
        soql += ' WHERE ';
        soql += '  recordtype.DeveloperName in (\'RecordType_SteelCons\',\'RecordType_Steel_sales\')';
        if(!Test.isRunningTest()){soql += '  AND (ThisWeekActive__c != NULL OR Last2WeekActive__c != NULL OR LastWeekActive__c != NULL)';}

        return soql;
    }
}