force-app/main/default/objects/Opportunity/fields/ST_chakkou__c.field-meta.xml
<CustomField>
    <fullName>ST_chakkou__c</fullName>
    <label>工期_着工</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_suryou__c.field-meta.xml
<CustomField>
    <fullName>ST_suryou__c</fullName>
    <label>数量(t)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ST_syukou__c.field-meta.xml
<CustomField>
    <fullName>ST_syukou__c</fullName>
    <label>工期_竣工</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/transtionDateToPhaseJuchuST__c.field-meta.xml
<CustomField>
    <fullName>transtionDateToPhaseJuchuST__c</fullName>
    <label>内定日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/RecordType_SteelCons.recordType-meta.xml
<RecordType>
    <fullName>RecordType_SteelCons</fullName>
    <active>true</active>
    <businessProcess>野原スチール_工事部</businessProcess>
    <label>スチール_工事</label>
</RecordType>

force-app/main/default/classes/NHR_ST_OppSteelDeliveryCtrlTest.cls
@isTest
public class NHR_ST_OppSteelDeliveryCtrlTest {
    public class InputParam {
        @InvocableVariable(required=true)
        public Id recordId;
    }
    @isTest static void test() {
        
        String StId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('RecordType_SteelCons').getRecordTypeId();
        Opportunity opp = new Opportunity(Name = 'ST商談' , RecordTypeId = StId,StageName = 'A' ,transtionDateToPhaseJuchuST__c =  Date.Today().addMonths(1)
                                          ,CloseDate =  Date.Today().addMonths(1) , ST_suryou__c = 10
                                          ,ST_chakkou__c =Date.Today().addMonths(-10) ,ST_syukou__c = Date.Today() );
        insert opp;
        List<NHR_ST_OppSteelDeliveryCtrl.InputParam> ins = new List<NHR_ST_OppSteelDeliveryCtrl.InputParam>();
        NHR_ST_OppSteelDeliveryCtrl.InputParam inO = new NHR_ST_OppSteelDeliveryCtrl.InputParam();
        inO.recordId = opp.Id;
        ins.add(inO);
        NHR_ST_OppSteelDeliveryCtrl.exec(ins);
        
        
    }
}