force-app/main/default/objects/JU_Category__c/JU_Category__c.object-meta.xml
<CustomObject>
    <label>住環境_カテゴリ別</label>
    <nameField>
        <displayFormat>J-{0000000000}</displayFormat>
        <label>住環境_カテゴリ別名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JU_Category__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>住環境_カテゴリ別</relationshipLabel>
    <relationshipName>JU_CategoryAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JU_Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>カテゴリ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JU_Category__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>商談</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>住環境_カテゴリ別</relationshipLabel>
    <relationshipName>Ju_Opportunitys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JU_Category__c/fields/OppStatus__c.field-meta.xml
<CustomField>
    <fullName>OppStatus__c</fullName>
    <label>商談フェーズ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JU_Category__c/fields/T1_Account__c.field-meta.xml
<CustomField>
    <fullName>T1_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先_T1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>住環境_カテゴリ別 (取引先_T1)</relationshipLabel>
    <relationshipName>JU_CategoryAccountT1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JU_ProposedProduct__c/JU_ProposedProduct__c.object-meta.xml
<CustomObject>
    <label>提案商品</label>
    <nameField>
        <label>提案商品名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JU_ProposedProduct__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>カテゴリ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>作図積算BPO</fullName>
            </value>
            <value>
                <fullName>生コン</fullName>
            </value>
            <value>
                <fullName>鉄筋</fullName>
            </value>
            <value>
                <fullName>基礎資材その他</fullName>
            </value>
            <value>
                <fullName>構造プレカット</fullName>
            </value>
            <value>
                <fullName>構造パネル</fullName>
            </value>
            <value>
                <fullName>羽柄材</fullName>
            </value>
            <value>
                <fullName>構造その他</fullName>
            </value>
            <value>
                <fullName>木材</fullName>
            </value>
            <value>
                <fullName>床断熱材</fullName>
            </value>
            <value>
                <fullName>壁天断熱材</fullName>
            </value>
            <value>
                <fullName>床壁天断熱材</fullName>
            </value>
            <value>
                <fullName>サッシ</fullName>
            </value>
            <value>
                <fullName>石膏ボード</fullName>
            </value>
            <value>
                <fullName>軽天材</fullName>
            </value>
            <value>
                <fullName>内装建材</fullName>
            </value>
            <value>
                <fullName>住設機器</fullName>
            </value>
            <value>
                <fullName>電気設備</fullName>
            </value>
            <value>
                <fullName>外装材</fullName>
            </value>
            <value>
                <fullName>外構資材</fullName>
            </value>
            <value>
                <fullName>副資材</fullName>
            </value>
            <value>
                <fullName>物流費</fullName>
            </value>
            <value>
                <fullName>荷揚げ費</fullName>
            </value>
            <value>
                <fullName>工事・サービス</fullName>
            </value>
            <value>
                <fullName>一括納材</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
            <value>
                <fullName>基礎資材</fullName>
                <isActive>false</isActive>
                <label>基礎資材</label>
            </value>
            <value>
                <fullName>断熱材</fullName>
                <isActive>false</isActive>
                <label>断熱材</label>
            </value>
            <value>
                <fullName>構造関連</fullName>
                <isActive>false</isActive>
                <label>構造関連</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JU_ProposedProduct__c/fields/Oppotunity__c.field-meta.xml
<CustomField>
    <fullName>Oppotunity__c</fullName>
    <label>商談</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>提案商品</relationshipLabel>
    <relationshipName>OppotunityProposedProduct</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FirstEstimates__c.field-meta.xml
<CustomField>
    <fullName>FirstEstimates__c</fullName>
    <label>初回見積提出日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/JU_category__c.field-meta.xml
<CustomField>
    <fullName>JU_category__c</fullName>
    <label>6カテゴリ種別</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01.基礎資材_生コン</fullName>
            </value>
            <value>
                <fullName>02.基礎資材_鉄筋</fullName>
            </value>
            <value>
                <fullName>03.構造材</fullName>
            </value>
            <value>
                <fullName>04.断熱材</fullName>
            </value>
            <value>
                <fullName>05.石膏ボード</fullName>
            </value>
            <value>
                <fullName>06.鋼製下地</fullName>
            </value>
            <value>
                <fullName>07.外構</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/T1_Account__c.field-meta.xml
<CustomField>
    <fullName>T1_Account__c</fullName>
    <formula>HYPERLINK(&apos;https://forcecom175.lightning.force.com/lightning/r/Account/&apos; + Account.ParentId + &apos;/view&apos;  , Account.Parent.Name ,&apos;_blank&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>親取引先</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NHR_JU_CategoryReportBatch.cls
/*
*住環境_カテゴリ別レポートの作成
*/
global without sharing class NHR_JU_CategoryReportBatch implements Database.Batchable<sObject>, Database.Stateful{

    global NHR_JU_CategoryReportBatch(){
    }
    //データ取得
    global Database.QueryLocator start(Database.BatchableContext BC){
        system.debug('NHR_JU_CategoryReportBatch');

    	String query = NHR_Dao.get_NHR_JU_CategoryReportBatch();
        return Database.getQueryLocator(query);
    }

    //開始
    global void execute(Database.BatchableContext BC, List<Opportunity> scopes){
        List<JU_Category__c> insList = new List<JU_Category__c>();
        For(Opportunity opp : scopes){
            JU_Category__c obj = new JU_Category__c();
            obj.Opportunity__c = opp.Id;
            obj.Account__c  = opp.AccountId;
            obj.T1_Account__c = opp.Account.ParentId;
            obj.OppStatus__c = opp.StageName;
            obj.FirstEstimates__c = opp.FirstEstimates__c;
            IF(opp.OppotunityProposedProduct__r != NULL && opp.OppotunityProposedProduct__r.size() > 0){
                obj.Category__c = opp.OppotunityProposedProduct__r[0].Category__c;
            }
            insList.add(obj);
        }
        insert insList;
    }

     //完了
    global void finish(Database.BatchableContext BC)
    {

    }

}