force-app/main/default/objects/ST_ManagementDashboard__c/ST_ManagementDashboard__c.object-meta.xml
<CustomObject>
    <label>スチール経営ダッシュボード用</label>
    <nameField>
        <label>スチール経営ダッシュボード名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>顧客名</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>スチール経営ダッシュボード用</relationshipLabel>
    <relationshipName>AccountDashboards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <label>顧客名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/Current10_Orig__c.field-meta.xml
<CustomField>
    <fullName>Current10_Orig__c</fullName>
    <label>当期10月_元値</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/Current11_Orig__c.field-meta.xml
<CustomField>
    <fullName>Current11_Orig__c</fullName>
    <label>当期11月_元値</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/Current12_Orig__c.field-meta.xml
<CustomField>
    <fullName>Current12_Orig__c</fullName>
    <label>当期12月_元値</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/Current1_Orig__c.field-meta.xml
<CustomField>
    <fullName>Current1_Orig__c</fullName>
    <label>当期1月_元値</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/Current2_Orig__c.field-meta.xml
<CustomField>
    <fullName>Current2_Orig__c</fullName>
    <label>当期2月_元値</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/Current3_Orig__c.field-meta.xml
<CustomField>
    <fullName>Current3_Orig__c</fullName>
    <label>当期3月_元値</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/Current4_Orig__c.field-meta.xml
<CustomField>
    <fullName>Current4_Orig__c</fullName>
    <label>当期4月_元値</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/Current5_Orig__c.field-meta.xml
<CustomField>
    <fullName>Current5_Orig__c</fullName>
    <label>当期5月_元値</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/Current6_Orig__c.field-meta.xml
<CustomField>
    <fullName>Current6_Orig__c</fullName>
    <label>当期6月_元値</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/Current7_Orig__c.field-meta.xml
<CustomField>
    <fullName>Current7_Orig__c</fullName>
    <label>当期7月_元値</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/Current8_Orig__c.field-meta.xml
<CustomField>
    <fullName>Current8_Orig__c</fullName>
    <label>当期8月_元値</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/Current9_Orig__c.field-meta.xml
<CustomField>
    <fullName>Current9_Orig__c</fullName>
    <label>当期9月_元値</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>日付</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/Num__c.field-meta.xml
<CustomField>
    <fullName>Num__c</fullName>
    <label>件数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/PhaseST__c.field-meta.xml
<CustomField>
    <fullName>PhaseST__c</fullName>
    <label>フェーズ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>受注</fullName>
                <color>#3366FF</color>
                <label>受注</label>
            </value>
            <value>
                <fullName>AB</fullName>
                <color>#33FFFF</color>
                <label>AB</label>
            </value>
            <value>
                <fullName>CD</fullName>
                <color>#78C953</color>
                <label>CD</label>
            </value>
            <value>
                <fullName>EF</fullName>
                <color>#66FF99</color>
                <label>EF</label>
            </value>
            <value>
                <fullName>GH</fullName>
                <color>#FF6600</color>
                <label>GH</label>
            </value>
            <value>
                <fullName>失注</fullName>
                <color>#FF0000</color>
                <label>失注</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/ReportType2__c.field-meta.xml
<CustomField>
    <fullName>ReportType2__c</fullName>
    <label>レポート区分2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/ReportType__c.field-meta.xml
<CustomField>
    <fullName>ReportType__c</fullName>
    <label>レポート区分</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/X1__c.field-meta.xml
<CustomField>
    <fullName>X1__c</fullName>
    <label>区分1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ST_ManagementDashboard__c/fields/X2__c.field-meta.xml
<CustomField>
    <fullName>X2__c</fullName>
    <label>区分2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ST_Opportunity_Snapshot__c/ST_Opportunity_Snapshot__c.object-meta.xml
<CustomObject>
    <label>商談_スナップショット_ST</label>
    <nameField>
        <displayFormat>STO-{0000000000}</displayFormat>
        <label>商談_スナップショット_ST</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ST_Opportunity_Snapshot__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>取引先ID(18桁)</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ST_Opportunity_Snapshot__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <label>取引先名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ST_Opportunity_Snapshot__c/fields/StageName__c.field-meta.xml
<CustomField>
    <fullName>StageName__c</fullName>
    <label>フェーズ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ST_Phase</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/NHR_ST_OppSnapshotDashboardBatch4.cls
/*
 * 【ST】スチール経営ダッシュボード
 * ■追及物件「件数」と「確度」月別推移
 */
global without sharing class NHR_ST_OppSnapshotDashboardBatch4 implements Database.Batchable<sObject>, Database.Stateful{
   
    global NHR_ST_OppSnapshotDashboardBatch4(){}
    global Map<String ,ST_ManagementDashboard__c> reportMap1 {get;set;}
    //global List<String> type1List{get;set;}
    //global List<String> type2List{get;set;}


    //データ取得
    global Database.QueryLocator start(Database.BatchableContext BC){
        system.debug('NHR_ST_OppSnapshotDashboardBatch4');

        //type1List = new List<String>{'1_全体' ,'2_事業一部' ,'3_事業二部'};
        //type2List = new List<String>{'AB' ,'CD' ,'EF','GH' ,'失注' ,'受注'};

        //setInit();
        String query = NHR_Dao.get_NHR_ST_OppSnapshotDashboardBatch4();
        return Database.getQueryLocator(query);
    }

    //開始
    global void execute(Database.BatchableContext BC, List<ST_Opportunity_Snapshot__c> scopes){

        List<ST_ManagementDashboard__c> tempInfoList = new List<ST_ManagementDashboard__c>();
        for(ST_Opportunity_Snapshot__c obj : scopes) {
            ST_ManagementDashboard__c tempInfo = new ST_ManagementDashboard__c();
            ST_ManagementDashboard__c tempInfo_sum = new ST_ManagementDashboard__c();


            String keyStr = obj.StageName__c;
            if (keyStr == 'A' || keyStr == 'B') {
                keyStr = 'AB';
            } else if (keyStr == 'C' || keyStr == 'D') {
                keyStr = 'CD';
            } else if (keyStr == 'E' || keyStr == 'F') {
                keyStr = 'EF';
            } else if (keyStr == 'G' || keyStr == 'H') {
                keyStr = 'GH';
            } else if (keyStr == '受注ST' || keyStr == '完成') {
                keyStr = '受注';
            } else if (keyStr == '辞退' || keyStr == '仕掛') {
                keyStr = '失注';
            } 


            tempInfo = setFC(NHR_Constant.BATCHNAME_ST_OSD3 + keyStr + obj.AccountId__c, '追及物件「件数」と「確度」月別推移_その他' , '重要取引先' ,obj, keyStr,'',0);
            tempInfo_sum = setFC(NHR_Constant.BATCHNAME_ST_OSD3 + keyStr + obj.AccountId__c, '追及物件「件数」と「確度」月別推移_その他' , '全体' ,obj, keyStr,'',0);
            tempInfoList.add(tempInfo);
            tempInfoList.add(tempInfo_sum);

        }
        
        insert tempInfoList;

    }

     //完了
    global void finish(Database.BatchableContext BC)
    {
        //system.debug('reportMap1.values();' + reportMap1.values());
        //insert reportMap1.values();
        
        mailSend();
    }
    
    /**
     * 初期設定
    
    private void setInit(){
        reportMap1 = new Map<String ,ST_ManagementDashboard__c>();
        
        //全体・事業
        Integer tempOrderNum0 = 100 ;
        Integer orderNum0 = 100 ;
        
        for(String str0 : type1List) {
            Integer s1 = 1;
            for (String str1 : type2List) {
                reportMap1.put(NHR_Constant.BATCHNAME_ST_OSD4 + str1 + str0 , setFC(NHR_Constant.BATCHNAME_ST_OSD4 + str1 + str0, '追及物件「件数」と「確度」月別推移_その他' , '全体' , str0,str0, str1,'',orderNum0));
                orderNum0 += 1;
                s1 += 1;
            }
            orderNum0 = tempOrderNum0 +  1000;
        }
       
    }
    */
    
    private ST_ManagementDashboard__c setFC(String Name , String ReportType ,String ReportType2 ,ST_Opportunity_Snapshot__c obj ,String Title2 ,String Title3 ,integer orderBy){
        ST_ManagementDashboard__c rec = new ST_ManagementDashboard__c();
        rec.Name = Name;
        rec.X1__c  = obj.AccountName__c;
        rec.X2__c  = Title2;
        rec.PhaseST__c  = Title2;
        if (ReportType2 == '全体') {
            rec.Department__c = ReportType2;
        } else {
            rec.Department__c = obj.Department__c;
        }
        
        rec.ReportType__c = ReportType;
        rec.ReportType2__c = ReportType2;
        rec.Date__c = Date.valueOf(obj.CreatedDate) ;
        rec.OrderBy__c = orderBy;
        rec.Num__c = 1;
        rec.Current1_Orig__c = 0;
        rec.Current2_Orig__c = 0;
        rec.Current3_Orig__c = 0;
        rec.Current4_Orig__c = 0;
        rec.Current5_Orig__c = 0;
        rec.Current6_Orig__c = 0;
        rec.Current7_Orig__c = 0;
        rec.Current8_Orig__c = 0;
        rec.Current9_Orig__c = 0;
        rec.Current10_Orig__c = 0;
        rec.Current11_Orig__c = 0;
        rec.Current12_Orig__c = 0;
        return rec;
    }
    
    /*
    * メール送信
    */
    private void mailSend(){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        mail.setToAddresses(new List<String>{UserInfo.getUserEmail()}); // 送信先(String[])
        
        mail.setSubject('【ST】スチール経営ダッシュボード゙作成処理完了のお知らせ'); // 件名(String)
        mail.setPlainTextBody('【ST】スチール経営ダッシュボード゙作成処理完了いたしました。'); // 本文(String)
        
        mail.setReplyTo(UserInfo.getUserEmail()); // 返信先メールアドレス(String)
        
        Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{mail});
    }

}